### ISSUE TITLE
Location should send relative url

### ISSUE THREAD

**Issue by kmjayadeep** [tus/tus-node-server#100]
In POST request, the response header should contain Location as relative url. In my case I was running application behind nginx proxy. So tus was returning 127.0.0.1/file_url in the Location. If it was relative url, it should be easy to handle for the client

**Comment by Acconut** [comment]
Historically, not all clients (especially on Android and iOS) have dealt very well if the URL returned in the Location header is not absolute. This is why we usually prefer to provide no relative URL. However, we would be happy to see a PR to change this.

**Comment by gormed** [comment]
@bhstahl I think this can be closed now :)

**Comment by bhstahl** [comment]
thanks @gormed  :)
