### ISSUE TITLE
nginx config for tus-node-server in a virtual machine

### ISSUE THREAD

**Issue by djsg** [tus/tus-node-server#107]
Hi,

This is my setting:
(1) web server (Laravel PHP, port HTTPS 443) and tus-node-server ((port 9000) run in a virtual machine (virtualbox)Ubuntu 16.04, IP address 192.168.10.10)
(2) Host machine (Ubuntu 16.04) IP address 10.217.131.132
(3) virtualbox redirect host machine port 44300 to virtual machine port 443
(4) in virtual machine nginx setting, I redirect "/files" to http://127.0.0.1:9000;

So in order to access my web server from other computer, I need to use URL(https://10.217.131.132:44300) and in tus-js-client I set endpoint to https://10.217.131.132:44300/files/. However, this setting does not work for me: always get some errors somewhere in upload.js.

What works for me is:
Use URL (https://192.168.10.10) to access my web server, and use https://192.168.10.10/files/ as endpoint in tus-js-client. The problem is that 192.168.10.10 is not known by other computers.

My guess is in order for the first case to work: there are some settings in nginx I need to get it right.

Can anybody help? Thx.

**Comment by Acconut** [comment]
> always get some errors somewhere in upload.js.

First of all, let's clarify what errors are you seeing. Saying "some" errors is not helpful, please be more descriptive. Then we can likely help you further.

**Comment by djsg** [comment]
@Acconut 
Sorry about being not-so-specific.

Today I did the test again with same settings:
I fixed endpoint in demo.js as
    var endpoint = "https://10.217.131.132:44300/files/";

The tus-node-server did receive the upload request because I saw in the log
    tus-node-server [TusServer] handle: POST /files/ +49m
however, my chrome browser showed this error message:

Failed to load https://10.217.131.132/files/e949bab288159e83d6e789fa1a886df5: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://10.217.131.132:44300' is therefore not allowed access.

I notice port 44300 is missing from response message.

**Comment by Acconut** [comment]
As you correctly noticed the port is missing in the response's Location header from the POST request. This is because neither tus-node-server nor nginx are aware that VirtualBox will do another port redirection. 

That could either be fixed in tus-node-server by changing that it does not return absolute URLs anymore (which contain the host and port) but instead only relative URLs (which just contain the pathname).

Alternatively, you could rewrite the Location header in the POST response inside nginx to contain the proper port. This may be the faster solution but is definitely not user friendly.

On the long run, I think, we should adjust tus-node-server to be more flexible here. What do you think?

**Comment by djsg** [comment]
Is it easy to change tus-node-server to use relative URLs? is it currently configurable?

For second option, as long as you provide configuration sample for both Apache and nginx, we, as users, are fine since we need to have either of them in case of using HTTPS to do file upload. 
BTW, do you have any working nginx sample config?

**Comment by djsg** [comment]
tentatively I run the tus-node-server code in host machine, then I use apache2 to forward HTTPS traffic with route "/files" to tus server. so far it works.

but there is a warning from nodejs:
(node:20367) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Do you want me to open another issue for it?

**Comment by Acconut** [comment]
> Is it easy to change tus-node-server to use relative URLs? is it currently configurable?

No, not at the time of writing this. You can see (https://github.com/tus/tus-node-server/blob/master/lib/handlers/PostHandler.js#L19) that not all used values there are configurable.

> Do you want me to open another issue for it?

Yes, please :+1:
