### ISSUE TITLE
Could not start tus server due to deprecated Google-Cloud package

### ISSUE THREAD

**Issue by michau-krakow** [tus/tus-node-server#113]
5 days ago the Google-Cloud package has been fully deprecated:
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2832

This makes tus-node-server unable to start as it can no longer `require('google-cloud')`;

**Comment by kvz** [comment]
Closed by accident or on purpose?

**Comment by michau-krakow** [comment]
I should have left some comment...
Closed intentionally, it looks deprecation affects older version and the latest one is working properly.
