### ISSUE TITLE
412 (Precondition Failed)

### ISSUE THREAD

**Issue by djsg** [tus/tus-node-server#114]
TUS server log: Invalid upload-metadata header: filename

TUS client error: see below captured image file
![1044288034](https://user-images.githubusercontent.com/11957578/42196510-e1440426-7eb0-11e8-9087-7b4c2caed0e7.jpg)

I am running the test in company Intranet. If I run clients in the same subnet as TUS server (10.217.131.xxx), it works perfectly; if I test client in other subnet (10.217.133.xxx), the above error appears.

I've tested 2 chunk sizes: infinity and 1000, both not working.
Where can I log the received HTTP message so I can compare?

**Comment by djsg** [comment]
I think I have the cause of this problem

At tus js client side, in file tus.js function encodeMetadata is like:

`function encodeMetadata(metadata) {
  if (!Base64.isSupported) {
    return "";
  }

  var encoded = [];

  for (var key in metadata) {
    encoded.push(key + " " + Base64.encode(metadata[key]));
    console.log("metadata key = " + key + ", value = " + metadata[key]);
  }

  return encoded.join(",");
}
`
Based on the console log, metadata are filename and filetype.
It is a **BUG**  in the case filetype value is an empty string, because at tus-node-server side, in file lib/Server.js at line 150

            if (RequestValidator.isInvalidHeader(header_name, req.headers[header_name])) {
                log(`Invalide header name: ${header_name}, value: ${req.headers[header_name]}`);
                invalid_headers.push(header_name);
            } else {
                log(`Valid header name: ${header_name}, value: ${req.headers[header_name]}`);
            }
When checking metadata, a non-empty string is expected.
In my test case, if at client side filetype value is empty, I got that 412 error.

**Comment by Acconut** [comment]
Thanks for investigating this. Let's continue the discussion in https://github.com/tus/tus-node-server/issues/117.

Also, please avoid mentioned too many people. Most of them are not involved in tus-node-server and won't be able to help you. We will always respond but it sometimes just takes a bit of time.

**Comment by djsg** [comment]
@Acconut  Sorry for including everyone.
