### ISSUE TITLE
Entity Header must not be empty

### ISSUE THREAD

**Issue by technicalbird** [tus/tus-node-server#115]
Hi,

I got this error while uploading files to local. 
For exact Error.
 https://drive.google.com/file/d/1kwHxvOiJgvgqZ7ibrUWKyJ-1FYoKiwja/view?usp=sharing Any help would be greatly appreciated. 

Thanks

**Comment by Acconut** [comment]
The Entity-Length header has been removed from the tus protocol a few years ago and is not referenced by tus-node-server (this repository) anymore. It seems as if you are using node-tus (https://github.com/niklasvh/node-tus) which has not been updated for four years and is not compatible with the current tus protocol. So I think you are confusing node-tus (old) and tus-node-server (not old). If you start using tus-node-server this error will not appear.

**Comment by technicalbird** [comment]
Could you please tell me where I could find the updated code. I need to bind this for both client and for server. Please help

**Comment by technicalbird** [comment]
Thanks, that issue has been resolved.
But I got one more,
Is there any way I could send additional parameters with file and save the file with the format it has?

**Comment by Acconut** [comment]
Closing this issue since the author moved the further discussion to #118.
