### ISSUE TITLE
Upload-Metadata BUG in tus js client code

### ISSUE THREAD

**Issue by djsg** [tus/tus-node-server#117]
At tus js client side, in file tus.js function encodeMetadata is like:

```js
     function encodeMetadata(metadata) {
        if (!Base64.isSupported) {
          return "";
        }

        var encoded = [];

        for (var key in metadata) {
          encoded.push(key + " " + Base64.encode(metadata[key]));
          console.log("metadata key = " + key + ", value = " + metadata[key]);
        }

        return encoded.join(",");
    }
```

Based on the console log, metadata are filename and filetype.
It is a BUG in the case filetype value is an empty string, because at tus-node-server side, in file lib/Server.js at line 150

```js
            if (RequestValidator.isInvalidHeader(header_name, req.headers[header_name])) {
                log(`Invalide header name: ${header_name}, value: ${req.headers[header_name]}`);
                invalid_headers.push(header_name);
            } else {
                log(`Valid header name: ${header_name}, value: ${req.headers[header_name]}`);
            }
```

When checking metadata, a non-empty string is expected.
In my test case, if at client side filetype value is empty, I got 412 (Precondition Failed) error.

**Comment by Acconut** [comment]
Good catch, @djsg, thank you for digging into this. Would you be so kind and provide a PR for allowing empty metadata in tus-node-server?

**Comment by djsg** [comment]
@Acconut 
PR means permanent resolution? I can give it a try.
My current solution is that at client side if filetype value is empty, I assign "unknown type" to it.
A proper way should be at server side allowing empty metadata values.
Is there a deadline? how to submit my code?

**Comment by Acconut** [comment]
> PR means proper resolution? I can give it a try.

PR stands for Pull Request which is the way how one can contribute on GitHub. It basically means that you *request* that we *pull* your code changes into our repository.

> A proper way should be at server side allowing empty metadata values.

Exactly, that would be the better solution

> Is there a deadline?

No, there is no deadline :)

> how to submit my code?

I am unsure how familiar you are with GitHub but here is a detailed guide on how you can contribute code: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ If you have any questions feel free to ask me. Also if you don't get that guide working, you can also e-mail your changes at marius@transloadit.com

**Comment by djsg** [comment]
Hi @Acconut, I followed that guide and submitted a PR.

**Comment by djsg** [comment]
@Acconut 
sorry, not sure how to run the build system locally. and my changes cannot pass the system test.

**Comment by Acconut** [comment]
Thank you very much @djsg. I merged your PR, so this should hopefully be fixed now
