### ISSUE TITLE
How to send additional parameters with request and return Response?

### ISSUE THREAD

**Issue by technicalbird** [tus/tus-node-server#118]
Hi, 
I want to know how can I send additional paramters like user related information in this, So that it becomes less handy to manage things at server.

Also, I would need help regarding the name of file gets printed in console to be converted as output JSON. i.e Name of saved file in the repsonse 
please help.

**Comment by Acconut** [comment]
> I want to know how can I send additional paramters like user related information in this

Assuming that you are using tus-js-client, you can use the `metadata` option (see https://github.com/tus/tus-js-client#tusdefaultoptions) to supply key-value-pairs with any information you want. This can then be accessed in tus-node-server's events.

> Also, I would need help regarding the name of file gets printed in console to be converted as output JSON. i.e Name of saved file in the repsonse

Sorry, I don't understand what you are exactly asking? Would you mind rephrasing that?

**Comment by technicalbird** [comment]
OK, There is lot of confusion in the git repo for both client and server. The example for client posted in n

> [https://github.com/tus/tus-node-server]( Tus node) does not work and server side posted in [Tus Client](url) does not work.

The only solution that seems to work is by using the client side of Tus client and server side for tus Node. But this is not the end, when you try to upload something, you got the CORS error. Using Google Chrome plugin I managed to solve this ( but that is not the solution). 

Now, Coming to the point you said. Check this out

Thi is what I used on client side,```

var upload = new tus.Upload(file, {
        endpoint: endpointInputEl.value,
        retryDelays: [0, 1000, 3000, 5000],
        metadata: {
            filename: file.name,
            filetype: file.type,
            user_id:"customized"
        },
        onError: function(error) {
            console.log("Failed because: " + error)
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
            console.log(bytesUploaded, bytesTotal, percentage + "%")
        },
        onSuccess: function() {
            console.log("Download %s from %s", upload.file.name, upload.url)
        }
    })

    // Start the upload
    upload.start()
```

On server Side
```

```
server.on(EVENTS.EVENT_FILE_CREATED, (event) => {
    console.log(`Upload file created for file`);
    console.log(event.file);
});

server.on(EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {

    console.log(`[${new Date().toLocaleTimeString()}] [EVENT HOOK] Upload complete for file ${event.file.id}`);
});
```
& this is the console 
File {
  id: 'd1813080d6cfe8758874e472c3ed23c0',
  upload_length: '101772',
  upload_defer_length: undefined,
  upload_metadata: 'filename QmViYXNOZXVlIEJvbGQub3Rm,filetype YXBwbGljYXRpb24vdm5kLm9hc2lzLm9wZW5kb2N1bWVudC5mb3JtdWxhLXRlbXBsYXRl,user_id Y3VzdG9taXplZA==' }

The user id is encrypted, and it's base 64. So, I managed to get the user id on Server side.

> 
I am posting this for others So that they don't gets confused.

Now the last solution I want is what should I do with CORS ERROR

**Comment by Acconut** [comment]
> The example for client posted in https://github.com/tus/tus-node-server does not work and server side posted in Tus Client does not work.

What exactly did not work? We are not aware of any flaws in these examples but we are always happy to see how we can avoid the confusion? FYI, tus-js-client does not have a server-side, so what are you referring to?

>  Now the last solution I want is what should I do with CORS ERROR

tus-node-server will set the necessary CORS headers, including Access-Control-Allow-Origin. Are you using some proxy in between which could alter the request and response headers?

**Comment by technicalbird** [comment]
Here is the test case for creating the confusion
- Clone both of the repo
- Try to run them

& that's exactly similar to what a normal user does. 

Regarding CORS
Also, there is also [issue](https://github.com/tus/tus-js-client/issues/110) posted in client repo and I am not using any proxy.

**Comment by Acconut** [comment]
Ok, I see what confusion you are referring to. Both projects use different port numbers, so you have to configure them first.

> Also, there is also issue posted in client repo

I don't see how that issue should be connected to your situation. Would you mind to elaborate?

> I am not using any proxy.

Ok, thanks. What endpoint are you passing to tus-js-client? `http://localhost:8000/` or `http://localhost:8000/files/`? If you are not using latter one, please try it out.

If that doesn't help please generate a HAR file (see https://www.inflectra.com/support/knowledgebase/kb254.aspx) after trying to upload. This file contains all network requests making it easier for us to debug your issue. You can either attach this file to this discussion or mail it me at marius@transloadit.com

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
