### ISSUE TITLE
Security vulnerabilities introduced through pinned version of @google-cloud/storage

### ISSUE THREAD

**Issue by spencern** [tus/tus-node-server#119]
We use the `snyk` tool at ReactionCommerce to scan for vulnerabilities reported in npm packages.

We're seeing two different vulnerabilities introduced through `tus-node-server` and both of them are coming through the outdated dependency on @google-cloud/storage@1.1.1

A medium severity vulnerability on tunnel-agent: https://snyk.io/vuln/npm:tunnel-agent:20170305
```
tus-node-server@0.2.11 > @google-cloud/storage@1.1.1 > gcs-resumable-upload@0.7.7 > google-auto-auth@0.6.1 > gcp-metadata@0.1.0 > retry-request@1.3.2 > request@2.76.0 > hawk@3.1.3 > hoek@2.16.3
```

A low severity vulnerability on hoek: https://snyk.io/vuln/npm:hoek:20180212
```
tus-node-server@0.2.11 > @google-cloud/storage@1.1.1 > gcs-resumable-upload@0.7.7 > google-auto-auth@0.6.1 > gcp-metadata@0.1.0 > retry-request@1.3.2 > request@2.76.0 > tunnel-agent@0.4.3
```

After splunking through the @google-cloud/storage releases, it seems that if you can update to v1.7.0 of `@google-cloud/storage` that should bump the version of `request` enough to eliminate these vulnerabilities. 

Version 0.11 of `gcs-resumable-upload` contains a different auth library than google-auto-auth which should also resolve the vulnerabilities, but is not yet available in any `@google-cloud/storage` releases yet.

**Comment by Acconut** [comment]
Thank you very much reporting this. Would you mind opening a pull request for upgrading `@google-cloud/storage`? This patch can then be included in the 0.3.0 release which is right around the corner.

**Comment by spencern** [comment]
@Acconut There's a new vulnerability reported in the `cryptiles` library that's included in the `@google-cloud/storage@1.1.1` release. That vuln is also resolved by #120. 

When do you think you'll be able to cut a release?

**Comment by Acconut** [comment]
0.3.0 has just been released right now.

**Comment by spencern** [comment]
Thank you!
