### ISSUE TITLE
Create S3DataStore

### ISSUE THREAD

**Issue by nodesocket** [tus/tus-node-server#12]
We are looking at using tus-node-server for our file uploads. Excited to try it out. Happy to help out with a s3 storage backend plugin, can anybody give guidance on where to start?

**Comment by kvz** [comment]
Happy to hear! @bhstahl should be able to give you some pointers into this

**Comment by bhstahl** [comment]
@nodesocket Awesome! Would love to have some help, and some input on the overall design of this.

My train of thought is having an abstract [DataStore](https://github.com/tus/tus-node-server/blob/master/lib/stores/DataStore.js), not tied to the server code, which defines an interface (that the server understands) and has methods to create the file, accept chunks, etc.

Then, each storage backend, such as the local [FileStore](https://github.com/tus/tus-node-server/blob/master/lib/stores/FileStore.js), S3, GCS will subclass the DataStore and implement their respective setup. 

This allows the actual [server code](https://github.com/tus/tus-node-server/blob/master/lib/Server.js) to remain dumb, and based on your DataStore choice, it will define what your server supports [like so](https://github.com/tus/tus-node-server/blob/6c363db16b783122746620afa48bb8f3b436d301/lib/stores/FileStore.js#L21). The `OPTION` handler [reads from the DataStore's extensions](https://github.com/tus/tus-node-server/blob/6c363db16b783122746620afa48bb8f3b436d301/lib/handlers/OptionsHandler.js#L28-L30) and informs the requestor.

My early notes on this are in #10 but totally open to your ideas!

**Comment by nodesocket** [comment]
Abstract DataStore makes sense. So would the s3 storage just implement `create()` which would push to s3 basically?

**Comment by bhstahl** [comment]
Cool. I was thinking `create()` was for incoming [`POST` requests](http://tus.io/protocols/resumable-upload.html#post ), and doing the work of the [creation extension](https://github.com/tus/tus-node-server/blob/6c363db16b783122746620afa48bb8f3b436d301/lib/handlers/PostHandler.js#L39) and solely creating the file. 

I haven't gotten to it yet, but am planning a `write()` method for incoming [`PATCH` requests](http://tus.io/protocols/resumable-upload.html#patch) which would simply handle accepting data, and this case push it to S3. With S3's multipart, those writes could be in parallel and the S3Store would implement the [concatenation extension](http://tus.io/protocols/resumable-upload.html#concatenation) piecing it all together in something like a `complete()` method that gets called when the whole file is transferred.

**Comment by tolgaakyuz** [comment]
I'm also happened to be in a need for `s3datastore` at work. I'm currently working on an implementation, and would be happy to get it merged. if you guys have any concern or want me to address something, please let me know.

**Comment by anonimousse12345** [comment]
@tolgaakyuz Found this if it's any use?
https://github.com/blockai/s3-tus-store

 Haven't tested yet and don't know enough about Tus to know if it's a good implementation or not

**Comment by bhstahl** [comment]
Great! This works well with #61 actually. We can split `GCSDataStore` out into its own package as well. I can take a crack at that unless anyone else has a jump on it.

**Comment by rictorres** [comment]
anyone working on this? i'm implementing this internally here @mycujoo, could send a PR after it's tested in production 😅

**Comment by bhstahl** [comment]
That would be great @rictorres ! I started working on #69 as well a while back but got a bit busy with things. If you're interested, that would be a huge help.

**Comment by rictorres** [comment]
hey!

so, initial implementation is available at https://github.com/mycujoo/tus-node-server/pull/2
i'm gonna continue working on this so a fully working PR can be sent to this repo :)

let me know your thoughts, any feedback will be much appreciated ;)

/cc @bhstahl

**Comment by rictorres** [comment]
update:

we've been using `tus-node-server` together with `s3-store` for almost 6 months in production (https://mycujoo.tv). all major issues have been fixed.

whoever is interested, please check the source code on https://github.com/mycujoo/tus-node-server and send us some feedback :)

we'll be sending a pr to this repo soon.

thanks!

**Comment by benedictchen** [comment]
@rictorres Any update on that PR?

**Comment by rictorres** [comment]
i'll update that pr asap :)
thanks for reminding me

**Comment by dohomi** [comment]
@rictorres would love to see this feature as well. Any update on this?

**Comment by rictorres** [comment]
@dohomi afaik that pr is ready to be merged, at least it was 2.5 months ago :)

cc @bhstahl @Acconut

**Comment by dohomi** [comment]
cool I will use your fork meanwhile thanks!

**Comment by Acconut** [comment]
Thanks for all the work! #89 has been merged :tada:
