### ISSUE TITLE
expose File model

### ISSUE THREAD

**Issue by SavePointSam** [tus/tus-node-server#122]
I'm needing to create my own `DataStore` based on `FileStore`. However, there appears to be no entry to get to the `File` model used by this library. I now need to either duplicate my code or (maybe) use an unsupported entry point.

If the `File` model could be exposed to the public API, that would be awesome so that my custom `DataStore` works as the internal ones do.

Thanks!

**Comment by SavePointSam** [comment]
I just realized that `DataStore` has no reliance on Store#configstore, so there is no need for me to use your `File` model. Meaning this is a non-issue.


Original Answer:
I'm making a custom `Store` for working with HDFS. I'm not subclassing `FileStore`, I'm using it as a basis to build my own. I'm actually subclassing `DataStore` like all other `Store`s.

However, in order to remain compatible with `DataStore`, I need to make sure the `Store#configstore` I'm storing information into uses the same data model, which in this case is a direct instance of `File`.

**Comment by Acconut** [comment]
Ok, thanks for your explanation.
