### ISSUE TITLE
Unable to implement custom datastore

### ISSUE THREAD

**Issue by paschaldev** [tus/tus-node-server#125]
I've been battling with creating a custom DataStore for `Cloudinary` and I don;t know how to get past this error in the console when I try to start the server.

```
Error: [object Object] is not a DataStore
    at TusServer.set datastore [as datastore] (/Users/xyz/Documents/GitHub/tus-upload-test/node_modules/tus-node-server/lib/Server.js:70:19)
    at Object.<anonymous> (/Users/xyz/Documents/GitHub/tus-upload-test/server.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

### server.js
```js
const tus = require('tus-node-server');
const express = require('express');
const server = new tus.Server();

const CloudinaryStore = require('../tus-cloudinary-store/src/index')

server.datastore = new CloudinaryStore({
    path: '/files'
});

const app = express();
const uploadApp = express();
uploadApp.all('*', server.handle.bind(server));
app.use('/uploads', uploadApp);

const port = process.env.PORT || 1080;
app.listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on port: ${port}`); 
});
```

### CloudinaryStore.js

For a start, my cloudinary store looks like this 

```js 
'use strict'

const DataStore = require('tus-node-server/lib/stores/DataStore');
const cloudinary = require('cloudinary');

const assert = require('assert');
const File = require('tus-node-server/lib/models/File');

const ERRORS = require('tus-node-server/lib/constants').ERRORS;
const EVENTS = require('tus-node-server/lib/constants').EVENTS;
const TUS_RESUMABLE = require('tus-node-server/lib/constants').TUS_RESUMABLE;

const debug = require('debug');
const log = debug('tus-node-server:stores:cloudinarystore');

/**
* Cloudinary Store implementation for TUS
*
* @author Ezeugwu Paschal <ezeugwupaschal@gmail.com>
*/

class CloudinaryStore extends DataStore {

 	constructor(options){

 		super(options);

 		this.extensions = ['creation', 'creation-defer-length'];
 	}

  	/**
	* Called in POST requests. This method just creates a
	* file, implementing the creation extension.
	*
	* http://tus.io/protocols/resumable-upload.html#creation
	*
	* @param  {object} req http.incomingMessage
	* @return {Promise}
	*/
	create(req) {
		
		
	}

	/**
	* Called in PATCH requests. This method should write data
	* to the DataStore file, and possibly implement the
	* concatenation extension.
	*
	* http://tus.io/protocols/resumable-upload.html#concatenation
	*
	* @param  {object} req http.incomingMessage
	* @return {Promise}
	*/
	write(req) {
		
	}

	/**
	* Called in HEAD requests. This method should return the bytes
	* writen to the DataStore, for the client to know where to resume
	* the upload.
	*
	* @param  {string} id     filename
	* @return {Promise}       bytes written
	*/
	getOffset(id) {
		
	}
}

module.exports = CloudinaryStore
```

**Comment by Acconut** [comment]
That's a weird error, I was not able to reproduce using your scripts. However, I have an idea: From `require('../tus-cloudinary-store/src/index')` it looks like your `server.js` and `CloudinaryStore.js` are stored in different folders (/Users/xyz/Documents/GitHub/tus-upload-test/ and /Users/xyz/Documents/GitHub/tus-cloudinary-store) with their own node_modules folders. Therefore, both of these files end up requiring different tus-node-server modules. The result is that if one tus-node-server sees a DataStore object from another tus-node-server, it will not be able to recognize it as its own DataStore. I know this might be confusing, so feel free to ask if that's not understandable.

The solution might be to make sure that all files require the same tus-node-server. How to do that the best way depends on your setup.

**Comment by paschaldev** [comment]
@Acconut I understand you but the `tus-node-server` was installed with npm so it's same. Let me explain better.

I want to build the `CloudinaryStore` as a separate independent module so I can manage it rather that fork this current repository and make one then send the pull request. 

I tried implementing the custom store as a new kind of store under this repository so I can send a pull request and all worked fine, I didn't get that error. However, as an independent module, it stilll fails however the test passes.

I have this test case which passed. 
`assert.equal(new Cloudinary instanceof DataStore, true);`

I already published it on github, please pull the repo and try to use it as a custom store on node.js. When you try to start the upload server, it will fail with the error reported earlier.

[https://github.com/paschaldev/tus-cloudinary-store]

**Comment by paschaldev** [comment]
@Acconut UPDATE. I don't get the error when I `npm install` from the github repo. The error only happens when I'm building locally because I installed locally as `npm i ./documents/github/tus-cloudinary-store`.

What is the way out?

**Comment by paschaldev** [comment]
@Acconut I was able to get past that error using `npm link`. Closing this.

**Comment by Acconut** [comment]
Congrats on finding the issue :+1: I am glad to hear that it's working for you now
