### ISSUE TITLE
Chunk with parallel upload

### ISSUE THREAD

**Issue by paschaldev** [tus/tus-node-server#126]
I tested this server out with express using chunk uploads. I added this in my upload client header ('tus-js-client'). I am using S3 bucket

```
headers:{

            "Upload-Concat": "partial"
}
```
It works fine, it splits the file into chunks but unfortunately, this chunks are sent serially, one after the other. Is there a way to upload in parallel so the final file is concatenated?

Environment is the browser... 
Upload Server is node

**Comment by Acconut** [comment]
This is not related to tus-js-client and not tus-node-server. tus-js-client is currently not able to automatically splitting an upload into multiple parts and uploading them in parallel. In fact, setting the `Upload-Concat` header does not change the behavior of tus-js-client at all.
