### ISSUE TITLE
S3 Upload Restarts and never completes

### ISSUE THREAD

**Issue by paschaldev** [tus/tus-node-server#127]
I noticed anytime I try to upload to S3, teh upload progress restarts. I'm using partial upload with the header `Upload-Concat: "partial"`. When I use the FileStore, it works but Amazon S3 buckets gives this issue.

![image](https://user-images.githubusercontent.com/13323281/44090022-aeef9342-9fc0-11e8-93a5-701de09abc99.png)

### server.js 
```js
const tus = require('tus-node-server');
const express = require('express')
const path = require('path')
const fs = require('fs')
const spdy = require('spdy')
const cors = require('cors')
const uniqid = require('uniqid')
const mimeToExt = require('mime-to-extensions')
const fileExtension = require('file-extension');

const options = {
    key: fs.readFileSync(__dirname + '/server.key'),
    cert:  fs.readFileSync(__dirname + '/server.crt')
}

const parseMetadataString = (metadata_string) => {
    const kv_pair_list = metadata_string.split(',');
     return kv_pair_list.reduce((metadata, kv_pair) => {
        const [key, base64_value] = kv_pair.split(' ');
         metadata[key] = {
            encoded: base64_value,
            decoded: Buffer.from(base64_value, 'base64').toString('ascii'),
        };
         return metadata;
    }, {});
}

const fileNameFromUrl = (req) => {
    let metadata = parseMetadataString( req.headers['upload-metadata'] )

    return `${uniqid()}.${fileExtension( metadata.filetype.decoded )}`;
}
const server = new tus.Server();
server.datastore = new tus.S3Store({
    path: '/files',
    bucket: process.env.S3_BUCKET,
    accessKeyId: process.env.AWS_ACCESS,
    secretAccessKey: process.env.AWS_SECRET,
    region: 'us-east-1',
    partSize: 2000000,,
    tmpDirPrefix: 'tmp',
    namingFunction: fileNameFromUrl
});


const HEADERS = [
    'Authorization',
    'Content-Type',
    'Location',
    'Tus-Extension',
    'Tus-Max-Size',
    'Tus-Resumable',
    'Tus-Version',
    'Upload-Defer-Length',
    'Upload-Length',
    'Upload-Metadata',
    'Upload-Offset',
    'X-HTTP-Method-Override',
    'X-Requested-With',
    'Upload-Concat'
];

var corsOptions = {
    allowedHeaders: HEADERS
}

const app = express();
const uploadApp = express();
uploadApp.all('*', cors(corsOptions), server.handle.bind(server));
app.use('/uploads', uploadApp);

const PORT = process.env.PORT || 9000;

spdy
  .createServer(options, app)
  .listen(PORT, (error) => {
    if (error) {
        console.error(error)
        return process.exit(1)
    } else {
        console.log('Listening on port: ' + PORT + '.')
    }
  })
```

Using `tus-js-client`:
### uploader.js 

```js
import tus from 'tus-js-client'

const input = $("#uploadInput")

const $progress = $(".progress")

input.on("change", function(e) {
    // Get the selected file from the input element
    var file = e.target.files[0]

    // Create a new tus upload
    var upload = new tus.Upload(file, {
        endpoint: "https://localhost:9000/uploads/",
        retryDelays: [0, 1000, 3000, 5000],
        chunkSize: 20000000,
        removeFingerprintOnSuccess: true,
        metadata: {
            filename: file.name,
            filetype: file.type
        },
        headers:{

            "Upload-Concat": "partial"
        },
        onError: function(error) {
            console.log("Failed because: " + error)

            $progress.text("Failed")
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
            console.log(percentage + "%")

            $progress.text( percentage + "%" );
        },
        onSuccess: function() {

            console.log("Download %s from %s", upload.file.name, upload.url)
        }
    })

    // Start the upload
    upload.start()
})
```

After all that my server console reports this error 

```
Listening on port: 9000.
{ NotFound: null
    at Request.extractError (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/services/s3.js:557:35)
    at Request.callListeners (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/xyz/paschaldev/mpa/upload-server/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: null,
  code: 'NotFound',
  region: null,
  time: 2018-08-14T11:45:05.622Z,
  requestId: '9B05E2BA054FA467',
  extendedRequestId:
   'hVUkIh8A6ldNOvJcccV2AF/+GJC5o+lm1tQb7zQP3sWXLTDVwogPXKhn2nDEfdFcAKVTNHkWvqY=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 59.78611958314186 }
[S3Store] getOffset: No file found.
[S3Store] Request "close" event was emitted,however S3 was expecting more data. Failing gracefully...
```

**Comment by rictorres** [comment]
i'll try and have a look at it today and will get back to you in here

**Comment by paschaldev** [comment]
@rictorres I also noticed that if I put the direct URL instead of using an environment variable, it works. Weird but looks like the environment variable was causing the issue. I don't understand how possible that is.

**Comment by Acconut** [comment]
@paschaldev What environment variable are you referring to?

**Comment by Acconut** [comment]
`process.env` is not an environment variable but it's the object that contains all environment variables. These can be accesses as `process.env.PATH`. Which ones do you mean exactly?

**Comment by paschaldev** [comment]
I'm aware... Its process.env.AWS_SECRET process.env.AWS_ACCESS_KEY process.env.S3_BUCKET

**Comment by Acconut** [comment]
Ok, thanks. I am sorry but I am not expert at tus-node-server's S3Store. Maybe @rictorres has an idea?

**Comment by hchfly** [comment]
I have encountered the same problem。When I use s3 and  `resume` is true.  

I got something wrong message:
browser:    【tus-js-client】
`Request URL: http://localhost:1080/files/736f45ef6e9cfbf31f0768e5a6d189e3
Request Method: HEAD
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1080
Referrer Policy: no-referrer-when-downgrade`。

server:
`{ NoSuchUpload: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
    at Request.extractError (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message:
   'The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.',
  code: 'NoSuchUpload',
  region: null,
  time: 2018-09-10T13:25:04.481Z,
  requestId: 'D3168EF876ADD15B',
  extendedRequestId:
   'US5kLdUCcYETMYXLmVy3/JV4nU7rXI5S36Zx7M1A8D3G2qwWndOldUH20w0ySnor7l7cir6LrOg=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 58.48725473372862 }
[S3Store] getOffset: No file found.`

if `datastore` is `FileStore`,  it's works.    
But I have to use s3. How did you solve it? @paschaldev   and  @Acconut @rictorres

**Comment by rictorres** [comment]
i will double check as soon as possible.
