### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by nodesocket** [tus/tus-node-server#13]
We will need https support. Though, maybe we can just use an `ELB` in front of two tus-node-servers to load balance and terminate SSL there.

**Comment by kvz** [comment]
Does it have to be baked into the server itself? e.g. if you'd use an ssl terminator like haproxy/stunnel/nginx, you could run the tus server as a nonprivileged user (port > 1024), and also when the next heartbleed surfaces, that damage will be limited to the terminator - vs potentially leaking more sensitive data out of the tus process.

**Comment by kvz** [comment]
(i did read somewhere that node currently has the best ssllabs score compared to any other ssl implementation - by default - so that certainly helps. just trying to get a sense of what's really required)

**Comment by nodesocket** [comment]
I think your right, for us, since we use Amazon AWS, using a ELB in front of two tus-node-servers in different regions makes sense. We can terminate SSL on the ELB.
