### ISSUE TITLE
S3 Upload has a HEAD error

### ISSUE THREAD

**Issue by hchfly** [tus/tus-node-server#131]
Something:
1、Use sample code
2、When I use s3 in Server and `resume`【tus-js-client】   is true.
3、if `resume`【tus-js-client】 is false, it's works.

I got something error message:
browser: 【tus-js-client】
Request URL: http://localhost:1080/files/736f45ef6e9cfbf31f0768e5a6d189e3 Request Method: HEAD Status Code: 404 Not Found Remote Address: 127.0.0.1:1080 Referrer Policy: no-referrer-when-downgrade。

server【tus-node-server】:
{ NoSuchUpload: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. at Request.extractError (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/services/s3.js:577:35) at Request.callListeners (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:683:14) at Request.transition (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/state_machine.js:14:12) at /Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/request.js:685:12) at Request.callListeners (/Users/hchfly/Items/novocare/tus-node-server-master/node_modules/aws-sdk/lib/sequential_executor.js:115:18) message: 'The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.', code: 'NoSuchUpload', region: null, time: 2018-09-10T13:25:04.481Z, requestId: 'D3168EF876ADD15B', extendedRequestId: 'US5kLdUCcYETMYXLmVy3/JV4nU7rXI5S36Zx7M1A8D3G2qwWndOldUH20w0ySnor7l7cir6LrOg=', cfId: undefined, statusCode: 404, retryable: false, retryDelay: 58.48725473372862 } [S3Store] getOffset: No file found.

But I have to use s3 and  I don't know how to solve it?  @Acconut @rictorres

**Comment by Acconut** [comment]
Unfortunately, I am no expert at the S3 storage. Maybe @rictorres can help?

**Comment by rictorres** [comment]
yes, i will try and debug this :)

**Comment by it-fm** [comment]
not resolve ?

**Comment by Acconut** [comment]
AFAIK, this specific issue has not been investigated but the S3Store should be functional in most situation. Or do you have problems, @it-fm?

**Comment by rictorres** [comment]
i'm not experiencing this error from my end.

are you certain the upload ID `736f45ef6e9cfbf31f0768e5a6d189e3` is correct and exists in s3?

**Comment by harrisgeorge202** [comment]
ok

**Comment by hchfly** [comment]
oh!   I resolved it。  upload it to server  and then upload it to s3,  No problem in 2 years
