### ISSUE TITLE
EVENT_UPLOAD_COMPLETE emitted before file is ready to be read using GCS

### ISSUE THREAD

**Issue by kokokenada** [tus/tus-node-server#140]
In the event handler EVENT_UPLOAD_COMPLETE, I needed to add a sleep in order ro reliable read the GCS file that was just created.  GCS itself promises to be strongly globally consistent in "Read-after-write" https://cloud.google.com/storage/docs/consistency

**Comment by Acconut** [comment]
Thank you for reporting this. It should be fixed in https://github.com/tus/tus-node-server/commit/e0bbd6a5c80ce7293fdc3b80bbe2e1c2c3446f84. Would you be able to pull tus-node-server from master and confirm this?

**Comment by kokokenada** [comment]
@Acconut - I've just given it a try and it seems to be working better now.  I removed the pauses and my defensive retries didn't get invoked.
