### ISSUE TITLE
EPERM: operation not permitted, mkdir 'C:\Windows\system32\config\systemprofile\.config'

### ISSUE THREAD

**Issue by jsantos21** [tus/tus-node-server#143]
Hello guys,

I am having problems trying implement tus node server in my application.
Everything looks good until I use this function:

`server.datastore = new tus.FileStore({
  path: "./files"
});`

When I declare it, the server gives this error:
> EPERM: operation not permitted, mkdir 'C:\Windows\system32\config\systemprofile\.config'

Do you have any clue why that happens? A friend of mine, used it in Linux server and it worked fine, I am trying using it in a windows server.

Thanks in advance.

**Comment by Acconut** [comment]
tus-node-server uses the configstore module (https://github.com/yeoman/configstore/tree/v3.1.2) internally which creates a file inside the user's home directory for storing temporary data.

I am no Windows expert but could it be that you were trying to invoke tus-node-server as an administrator? Maybe you are able to run your program as another user and see if that works.

Alternatively, you should be able to control the directory where the file is created by adjusting the `XDG_CONFIG_HOME` environment variable.
