### ISSUE TITLE
How to enable chunked upload for GCS ?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [tus/tus-node-server#144]
Hello!

Sorry, I'm getting an error on client side. 
```
Request URL: http://localhost:8000/uploads.//7a3601af10ef9276f2fb1be9d84ace29
Request Method: PATCH
Status Code: 404 Not Found
Remote Address: 127.0.0.1:8000
```

I followed instructions on README. 
POST request goes just fine. 

```
Request URL: http://localhost:8000/uploads
Request Method: POST
Status Code: 201 Created
Remote Address: 127.0.0.1:8000
```

**Comment by Acconut** [comment]
> http://localhost:8000/uploads.//7a3601af10ef9276f2fb1be9d84ace29

This URL looks kind of strange to me. Are you sure it should not be http://localhost:8000/uploads/7a3601af10ef9276f2fb1be9d84ace29?

Also, just to be sure: Did you issue a POST request, which returned the URL http://localhost:8000/uploads.//7a3601af10ef9276f2fb1be9d84ace29, before issuing the PATCH request to http://localhost:8000/uploads.//7a3601af10ef9276f2fb1be9d84ace29? The POST endpoint is used to create an upload and must be issued before sending a PATCH request.

**Comment by AlexanderKozhevin** [comment]
The code is fine. I guess tus and google cloud uses different protocols for chunked upload. 

```
server.datastore = new tus.GCSDataStore({
    path: '/',
    projectId: 'parma-212715',
    keyFilename: './server/google_key.json',
    bucket: 'converter_storage',
});
```

**Comment by AlexanderKozhevin** [comment]
Upload-Offset conflict
```
Request URL: http://localhost:8000/uploads/files/fd94dd728ea605ba891decf3f8b5b9c8
Request Method: PATCH
Status Code: 409 Conflict
Remote Address: 127.0.0.1:8000
```
Post request passed just fine
```
Request URL: http://localhost:8000/uploads?name=anyfuckingname
Request Method: POST
Status Code: 201 Created
Remote Address: 127.0.0.1:8000
```

**Comment by AlexanderKozhevin** [comment]
@Acconut I think it's not a problem, but just question of architecture.

**Comment by Acconut** [comment]
I am sorry but I don't understand your question. Could you be more descriptive?

**Comment by AlexanderKozhevin** [comment]
@Acconut It's not a question :)
I'm just thinking that's it's not possible in this project.
