### ISSUE TITLE
Extension on upload doesnt show

### ISSUE THREAD

**Issue by rockyhuber** [tus/tus-node-server#145]
Hi I have uploaded a file using reactjs and nodejs. Using the following code:

```
const tus = require('tus-node-server');
const serverFile = new tus.Server();
serverFile.datastore = new tus.FileStore({
    path: '/files'
});

const express = require('express');
const app = express();
const uploadApp = express();
uploadApp.all('*', serverFile.handle.bind(serverFile));
app.use('/uploads', uploadApp);

const host = '127.0.0.1';
const port = 9000;
app.listen(port, host);
```

And for the reactjs component:
```
<input type={'file'} onChange={(e) => {
    // Get the selected file from the input element
    var file = e.target.files[0]
    // Create a new tus upload
    var upload = new tus.Upload(file, {
      endpoint: "http://localhost:9000/uploads/",
      retryDelays: [0, 1000, 3000, 5000],
      metadata: {
        filename: file.name,
        filetype: file.type
      },
      onError: function(error) {
        console.log("Failed because: " + error)
      },
      onProgress: function(bytesUploaded, bytesTotal) {
        var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
        console.log(bytesUploaded, bytesTotal, percentage + "%")
      },
      onSuccess: function() {
        console.log("Download %s from %s", upload.file.name, upload.url)
      }
    })
    // Start the upload
    upload.start()
}}/>
```
It uploads the file fine, however it doesn't upload the file with the adequate extension? I am new to tus and was using other modules before this. Where am I going wrong? I am using serverFile as there is already another server specified in the file elsewhere:
`const server = require('http').Server(app);`

**Comment by Acconut** [comment]
tus-node-server (and most other tus server) does not keep the keep the file extension. The reason is that you should not depend on the file extension as it might not be present or it might be completely wrong. Instead, you should attach the file type as metadata to your upload.

You are already doing this correctly on the client side (`metadata: { filetype: file.type }`). On the server side, you can use the event system (https://github.com/tus/tus-node-server#features) to be notified once an upload is complete and then extract the filetype from the metadata.

**Comment by rockyhuber** [comment]
Thanks! Did this.

**Comment by alexweltman** [comment]
@Acconut I am doing just this, however, S3 will set the content-type as application/octet-stream if the file has no extension. So, in the event handler for EVENT_UPLOAD_COMPLETE, I am using the file type I pass in the file metadata to set the S3 file content-type. But, S3 ONLY allows setting the content-type at the time of upload - it ignores subsequent update attempts to the content-type.

This means that trying to view uploaded images doesn't work (such as when right-clicking an image and selecting "view in new tab") - the browser can't detect the content-type, and initiates a download instead. This is a poor user experience.  Any suggestions on how I can set the s3 content-type at upload time?

**Comment by alexweltman** [comment]
Ah, I see this isn't documented anywhere, but in your comments you mention that contentType in the metadata is applied to the file in s3. I tried that, and it worked.
https://github.com/tus/tus-node-server/blob/4b44018d1cb1cc7c0c5c770f96581ef28c3cf1d9/lib/stores/S3Store.js

**Comment by Acconut** [comment]
@alexweltman Exactly, you can set the content type and filename using the metadata. Glad to read that you figured it out :+1:

**Comment by adrienfloor** [comment]
Hey @alexweltman
I'm currently trying to achieve what you're talking about here but I cant figure out where to put the content-type and how ...
Could you explain please ? It would help me a lot !
Thank you very much.

**Comment by Acconut** [comment]
@adrienfloor You need to put the content type into the metadata, like this:

```js
var upload = new tus.Upload(file, {
      endpoint: "http://localhost:9000/uploads/",
      retryDelays: [0, 1000, 3000, 5000],
      metadata: {
        contentType: file.type
      },
```

See https://github.com/tus/tus-node-server/blob/2f800162e8ea6e60682f0bc62b8fe5597dbc17a9/lib/stores/S3Store.js#L138

**Comment by adrienfloor** [comment]
Awesome, thanks a lot @Acconut !
