### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by SavePointSam** [tus/tus-node-server#149]
I've been happily using this package for around a year now. Thanks! However, I have started using TypeScript and it appears there are no types available for this package. I do not personally have the time to generate them myself, but I did want to track that there is desire for types be it either directly from this package or from a set of types made available from DefinitelyTyped.

**Comment by Acconut** [comment]
Thanks for the kind words! I agree that type definitions would be nice but we also currently don't have the resources for that. Maybe someone from the community could contribute that.

**Comment by Murderlon** [comment]
Closing this as there are types currently and we plan to rewrite the project to TS to further solidify this.
