### ISSUE TITLE
How to use uploaded files ?

### ISSUE THREAD

**Issue by keery** [tus/tus-node-server#151]
Hello,

I don't understand a point about uploaded files, in my context I upload images with uppy.
I achieve to upload them, but how to use them when they are uploaded because my files haven't extension.
Is there a given method already to retrieve files ?

Server
```
const server = new tus.Server();
server.datastore = new tus.FileStore({
    path : '/files',
});

dotenv.config();

const { PORT } = process.env;

const app = express();

app.set('port', PORT || 8080);

app.use(cors());

const uploadApp = express();
uploadApp.all('*', server.handle.bind(server));
app.use('/uploads', uploadApp);

app.use(compression());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended : false }));

app.listen(PORT, () => {
    logger.info(`App listening on port ${PORT}!`);
});

```

Client

```
this.uppy = new Uppy({
            id           : 'uppy-input',
            autoProceed  : true,
            debug        : true,
            restrictions : {
                maxFileSize      : 1000000,
                maxNumberOfFiles : 1,
                allowedFileTypes : ['image/*'],
            },
        })
            .use(Tus, {
                endpoint                   : `${process.env.SERVER_URL}/uploads`,
                resume                     : true,
                removeFingerprintOnSuccess : true,
                limit                      : 1,
            });
```

If anyone can help me ? Thanks in advance

**Comment by Acconut** [comment]
> I achieve to upload them, but how to use them when they are uploaded because my files haven't extension.

The files from tus uploads never have a file extension but you can use the upload's metadata to store the file's name. And then when the upload is finished you rename the binary file (whose name is the upload id) to the original filename with the extensions.

> Event value is "{ url: '//localhost:8000/files/ID_FILE' }" but when I try to call this url it doesn't work and the error message is "Not found"

Yes, because you likely didn't implement a GET request handler since tus-node-server doesn't provide that. See https://github.com/tus/tus-node-server#custom-get-handlers
