### ISSUE TITLE
Upload to s3 fails with error Unable to open.

### ISSUE THREAD

**Issue by shreykar** [tus/tus-node-server#156]
Upload to server works but uploading to s3 fails with error:
 Failed because: Error: tus: unexpected response while uploading chunk, originated from request (response code: 422, response text: Unable to open s3://mybucket/myfile.log)

I tried different requests to confirm s3 credentials and access such as putObject and deleteObject and both worked.
Also tried files of different sizes from a few KB to 50MB

Here is the code I am using:
$awsAccessKey = 'MY AWS KEY'; // YOUR AWS ACCESS KEY
$awsSecretKey = 'MY AWS SECRET'; // YOUR AWS SECRET KEY
$awsRegion    = 'ap-southeast-1';      // YOUR AWS BUCKET REGION
$basePath     = 's3://mybucket';

$s3Client = new S3Client([
    'version' => 'latest',
    'region' => $awsRegion,
    'credentials' => new Credentials($awsAccessKey, $awsSecretKey)
]);

$s3Client->registerStreamWrapper();

$server = new Server();
$server->setUploadDir($basePath);

$response = $server->serve();
$response->send();
exit(0);

**Comment by Acconut** [comment]
The code you posted is in PHP, so I assume this is not related to tus-node-server which is written in Node.js, right?
