### ISSUE TITLE
A Transform for this project to Typescript

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [tus/tus-node-server#158]
Ref to #64 #58  and #149 

Hi, @Acconut , i explore all the internet and i fined this project Tus , i see this project are years of disrepair , but i need use nodejs as server and js/ts as client.
so i create a copy of this project and try to translate all of it into Typescript.

you can have a look on this: https://github.com/Lyoko-Jeremie/tus-node-server

the transform are doing in progress. the main code base are done but the Test case dont. 
(because i unfamiliar about how to Test it, i need some times to learn many thing about it.
 Now i manual test it with tus-js-client use FileStorage on this project https://github.com/Lyoko-Jeremie/TestTus .)

i add the EVENT_CHUNK_UPLOADED event and MongoDB GridFS Backend to it because i need use the tus on a real project and i need a way to monitor all the progress and my project backend is Mongodb GFS.

the tslint not setup temporarily but i will add it soon. 
the PR about #64 are done by my ```PipListener``` , now it work for FileStorage but i will add it to other storage if i can .(the MongoGridFSStore will be add first if i test it work well.)

i writen a Reliable File Block Transport Protocol base Websocket for my real project at last two month, it with file hash verify like the Bittorrent to ensure the file complete AND some access control struct when connect setup to avoid server local disk fullfill attack And work with redis to keep distributied file lock work well.
when i turn to my Protocol after a holiday, i suddenly discovered that my protocal is so complex.
so i want to base on tus protocal and add some feature to this nodejs server implement ( example a plugin framework or something similar ) to make it can work on my real project.

**Comment by Acconut** [comment]
> i see this project are years of disrepair (..) try to translate all of it into Typescript.

Yes, this project has not been actively maintained in the past as we focus our efforts into tusd, the server implementation in Go. I am not sure if it's necessary to translate it to TypeScript since TS is able to read and use JavaScript files, as you probably know.

I am very amazed at how much effort you have already put into tus-node-server. However, I am not sure what you are trying to tell me here. Do you want to open PRs for these features or maintain your fork of tus-node-server separately?

**Comment by Lyoko-Jeremie** [comment]
@Acconut 
i was researched the document of tusd, but i cannot find a way to communit with the tusd to do the things that  -- when a new connect coming, tusd quest the manager the client have promission, and wait the manager get the distributied file lock on redis, and flush the distributied lock ever minute druing file transmisson *(because in my real project case, the files are video file and most of these size are 2 ~ 5 GiB and client connect usually only have a 0.5MiB/s upload bandwidth, so one file will use 3hours , and will have 4 ~ 50 files need to be transfer)* , and when complete transmission, tell the manager to use hash list to verify the whole file to ensure the file is ok and find which MB are broken druing transmission or case by user disk issue.


in another way, i recommend this project tus-node-server transform js into ts, because a big no type checked js project usually confuse people, example the ES Generation, the lint, the IDE support, the intelligent code complete, and so on.

so if i can, i try to mantaince a typescript version tus-node-server and put some future into it. but i know only myself is not enough to let it stable. so i want find some help from the community.

**Comment by Acconut** [comment]
> i was researched the document of tusd, but i cannot find a way to communit with the tusd to do the things that

Oh, that's totally possible. tusd has the hook system for that: https://github.com/tus/tusd/blob/master/docs/hooks.md

> i recommend this project tus-node-server transform js into ts

I don't agree here. Yes, TypeScript provides a lot of benefits (and I do like static typing, don't get me wrong). But it's also a big hurdle for new contributors to get started on this project. Besides knowing Node.js, one now must also understand how the TypeScript system works. Especially for a project, such as tus-node-server, which has seen little contribution in the past, I am not convinced that a conversion from JS to TS is the best investment of time.

> so if i can, i try to mantaince a typescript version tus-node-server and put some future into it. but i know only myself is not enough to let it stable. so i want find some help from the community.

I can only second that :) Getting more people on board is always a good idea :+1:

**Comment by Lyoko-Jeremie** [comment]
> Besides knowing Node.js, one now must also understand how the TypeScript system works. 

Sorry i don't think that.
Use ts can make more help when dev and the user don't need to care about it after ts compiled into a js lib.

After a typescript lib compile, it generate the .js file and .d.ts file. previous js user don't need to care about the .d.ts file , they can direct use the .js file like before . And in the same time, the user's IDE will auto read the .d.ts file to make intellisense and some tips in the back, example vscode or webstrom.

**Comment by Lyoko-Jeremie** [comment]
now you can try this: https://github.com/Lyoko-Jeremie/tus-node-server

i think this is stable, and it can be published to npm.
only to follow or run the ```generate.bat``` file to compile the TS into js, and then publish it to npm.

**Comment by Acconut** [comment]
> now you can try this: https://github.com/Lyoko-Jeremie/tus-node-server

Amazing work, thanks for sharing!
