### ISSUE TITLE
Tried but failed

### ISSUE THREAD

**Issue by avillarubia** [tus/tus-node-server#159]
Good day,

Some details:
node: v12.13.1

I tried to set up a file server but not luck
I've been through a lot of codes but always fail. I tried https://www.npmjs.com/package/tus-node-server but still no luck. I am looking for someone who can share a simple implementation.

This is my client on react js which successfully runs using the default endpoint: https://master.tus.io/files

```
import React, { useEffect } from "react";
import uppy from "../uploader/uploader";
import Tus from "@uppy/tus";
import { Dashboard } from "@uppy/react";

export function FileUploader() {
    useEffect(() => {
        uppy
            .use(Tus, { endpoint: "http://localhost:8081/uploads" })
            .on("complete", result => {
                const { uploadURL } = result.successful[0];
                console.log("Upload Successfully", uploadURL);
            });
        return () => {
            uppy.close();
        };
    }, []);

    return (
        <Dashboard
            uppy={uppy}
            width={500}
            height={10}
            note={"only accept image files"}
            hidePauseResumeButton={true}
            hideCancelButton={true}
            proudlyDisplayPoweredByUppy={false}
        />
    );
}
```

Thank you.

**Comment by Acconut** [comment]
There is an example available at https://github.com/tus/tus-node-server/blob/master/demo/server.js. Did you try that one? Also, if you provide us with error messages we might be able to help you resolve them.

**Comment by avillarubia** [comment]
@Acconut good day and thank you for the response. I tried that demo before but not working, I found out that I change the default 1080 to my desired port that makes it not working. I just use 1080 now and it is working after I deploy, but there is another problem, 

- it renames the file to something like a hex (410f462c9461ba67d469bc50bd03fcfa) without file extension. 
- it can't view the file through a return link after uploading http://ip:port/files/410f462c9461ba67d469bc50bd03fcfa (with or without extension)

Once again thank you.

**Comment by avillarubia** [comment]
@Acconut I guess I found the possible workaround

```
const server = new Server();
server.get('/uploads', (req, res) => {
    // Read from your DataStore
    fs.readdir(server.datastore.path, (err, files) => {
        // Format the JSON response and send it
    }
});
Custom file names:
const fileNameFromUrl = (req) => {
    return req.url.replace(/\//g, '-');
}

server.datastore = new tus.FileStore({
    path: '/files',
    namingFunction: fileNameFromUrl
});
```

**Comment by Acconut** [comment]
> I found out that I change the default 1080 to my desired port that makes it not working

You also have to change the port in the client's endpoint. Did you do that?

> the file server renames the file to something like a hex

That's expected, see https://github.com/tus/tus-node-server#custom-file-names and https://tus.io/faq.html#how-can-i-get-the-file-name-or-file-type-for-an-upload for a way to set custom file names.

**Comment by avillarubia** [comment]
@Acconut yes both client and server works. Thank you for the links you provided, very well appreciated
