### ISSUE TITLE
Implement to express

### ISSUE THREAD

**Issue by ReverseFlash28** [tus/tus-node-server#16]
How can I use this together with express?

**Comment by kvz** [comment]
I think the goal of this project is to have a stand-alone server of tus, although it has been some time that work was done here, did anything change on your end @bhstahl?

In the meantime, I think getting the tus-middleware project to 1.0 would be best. For reference:

https://github.com/foobarable/tus-middleware/issues/1#issuecomment-194296099
https://github.com/tus/tus-android-client/issues/4#issuecomment-194293352

**Comment by Acconut** [comment]
Actually, I believe it should already be possible to use tus-node-server with express. I haven't tested it thou:

```js
const server = new tus.Server();
server.datastore = new tus.FileStore({
    path: '/files'
});

app.all('/files/*', server.handle);
app.listen(PORT, HOST);
```
```

**Comment by bhstahl** [comment]
Correct! The server is designed work as a standalone, or to be used with any node web framework (Express, [Restify](http://restify.com/#common-handlers-serveruse)) that uses the [`IncomingMessage`](https://nodejs.org/api/http.html#http_class_http_incomingmessage) class of the [`http`](https://nodejs.org/api/http.html#http_http) module.

@kvz unfortunately our Q1 upload team roadmap got a bit hijacked by other projects, but tus in production is still a Q1 item, which at this juncture might unfortunately flow into April. We haven't lost sight though, a tus node server running with a local & GCS FileStore is on the horizon!

**Comment by kvz** [comment]
I stand corrected! And thanks for the update @bhstahl!

**Comment by ReverseFlash28** [comment]
@Acconut its not working :(

**Comment by bhstahl** [comment]
@ReverseFlash28 sorry, but that may be due to this still being a work in progress (which is why I haven't published it to NPM yet). You may want to check out https://github.com/foobarable/tus-middleware in the meantime, or contribute to the development here as well!

What version of Express are you running?

**Comment by ReverseFlash28** [comment]
@bhstahl I already use that but it makes me error when my client in android

**Comment by Acconut** [comment]
@bhstahl The reason why @ReverseFlash28 cannot use tus-middleware is that it does not support tus 1.0 which is a requirement for tus-android-client.

> its not working :(

What is not working? We need more information about what happened. Any errors?

**Comment by ReverseFlash28** [comment]
@Acconut your code 

`const server = new tus.Server();
server.datastore = new tus.FileStore({
    path: '/files'
});

app.all('/files/*', server.handle);
app.listen(PORT, HOST);`

**Comment by Acconut** [comment]
We cannot and will not help you if you don't provide us with details.
Showing us code and saying it doesn't work is not enough.
Am 11.03.2016 5:33 vorm. schrieb "Reverse Flash" <notifications@github.com>:

**Comment by ReverseFlash28** [comment]
this is the error

at Layer.handle [as handle_request] (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:131:13)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/username/Downloads/tus-node-server-master/node_modules/express/lib/router/route.js:125:14)

**Comment by makoy21** [comment]
@ReverseFlash28 

Try this one 

var app = express();
app.all('/files/*', function(req, res) {
    server.handle(req, res);
});
app.listen(port, host);

**Comment by ReverseFlash28** [comment]
ow thanks @makoy21 it's working! thanks.

**Comment by Acconut** [comment]
@makoy21 Thank you for providing your help :smile:

**Comment by kvz** [comment]
I think this might be useful to others so I just opened the PR to document this in our README https://github.com/tus/tus-node-server/pull/19
