### ISSUE TITLE
make public for a file only and disable public folder

### ISSUE THREAD

**Issue by avillarubia** [tus/tus-node-server#160]
Pardon that I should put this to question not issues. But, I didn't see the question section where I can post this.

what I want is to publicly view a single file like http://ip:port/files/uid
and
private when folder only http://ip:port/files/

Is this possible? Thank you for the answers

**Comment by Acconut** [comment]
I am not sure what Node.js framework you are using, but it should usually provide you with tools to restrict access to certain URLs. For example, using Express you can add a route for `/files/` and simply denied access.

tus-node-server is not concerned about access control, so it does not have a special feature for that.

**Comment by avillarubia** [comment]
@Acconut thank you
