### ISSUE TITLE
super long delay of file uploading. How to debug?

### ISSUE THREAD

**Issue by djsg** [tus/tus-node-server#163]
Hi,

I am experiencing unreasonably long delay in file uploading: 1.3M takes me 6 min.
Server side I used demo/server.js.
In client side, from Chrome console, I can see percentage info during progress.
Is it possible I log to stdout of similar info at server side? Which source file I should change to see that?

**Comment by vladut3pg** [comment]
There are a lot of reasons why this could happen. I would start investigating the chrome network tab. Limit the parallel uploads, check the chuncks to be reasonable in size, etc.
As a direct response you could take advantage of the events fired by the server on line 94.

**Comment by Acconut** [comment]
Good points, @vladut3pg!

Another important fact is what storage backend is used by @djsg (S3, GCS or disk)? If the connection to S3 is slow, tus-node-server's uploads will also be slow.

**Comment by djsg** [comment]
storage is disk.
what I can see now is that meta-data exchange is very fast.

**Comment by djsg** [comment]
I used "DEBUG=* node demo/server.js" to get the following debug message:
From line 6 to 7, there is a 5 minutes delay, which means . C

1.   tus-node-server Valid header name: tus-resumable, value: 1.0.0 +0ms
2.   tus-node-server Valid header name: upload-offset, value: 0 +1ms
3.   tus-node-server Valid header name: x-forwarded-for, value: 192.122.133.58 +0ms
4.   tus-node-server Valid header name: x-original-host, value: 558b7832.cpolar.io +0ms
5.   tus-node-server Valid header name: x-real-ip, value: 192.122.133.58:27914 +0ms
6.   tus-node-server handle: Access-Control-Allow-Origin +0ms
7.   tus-node-server:stores:filestore [FileStore] write: 10447378 bytes written to files/5bc2c00ab058d54ce39c7597816d22ce +0ms
8.   tus-node-server:stores:filestore [FileStore] write: File is now 10447378 bytes +0ms
9. [5:29:26 PM] [EVENT HOOK] Upload complete for file 5bc2c00ab058d54ce39c7597816d22ce

**Comment by djsg** [comment]
I used command "DEBUG=* node  demo/server.js" to run tus-node-server;
I change some of the log functions by adding current time for each log message;
and I got the following
...
1.   tus-node-server [2:12:57 PM.142] Valid header name: tus-resumable, value: 1.0.0 +0ms
2.   tus-node-server [2:12:57 PM.142] Valid header name: upload-offset, value: 0 +0ms
3.   tus-node-server [2:12:57 PM.142] Valid header name: x-forwarded-for, value: 192.122.133.58 +0ms
4.   tus-node-server [2:12:57 PM.143] Valid header name: x-original-host, value: 558b7832.cpolar.io +1ms
5.   tus-node-server [2:12:57 PM.143] Valid header name: x-real-ip, value: 192.122.133.58:57925 +0ms
6.   tus-node-server [2:12:57 PM.143] handle: Access-Control-Allow-Origin +0ms
7.   tus-node-server:stores:filestore [2:12:57 PM.146] [FileStore] getOffset: files/cd28c9543c1d6a7ce8c682cea78b8a61 OK! +1s
8.   tus-node-server:stores:filestore [2:12:57 PM.148] [FileStore] write file with offset 0 +2ms
9.   tus-node-server:stores:filestore [2:24:33 PM.215] [FileStore] write: 13677324 bytes written to files/cd28c9543c1d6a7ce8c682cea78b8a61 +12m
10.   tus-node-server:stores:filestore [2:24:33 PM.216] [FileStore] write: File is now 13677324 bytes +1ms
11. [2:24:33 PM.217] [EVENT HOOK] Upload complete for file cd28c9543c1d6a7ce8c682cea78b8a61
**From line 8 to 9, there is 12 minutes gap.**
Can anyone please tell me what the code is doing between line 8 and 9? Is it file transmission happening during that time or file writing to disk? Many thanks.

**Comment by Acconut** [comment]
I don't know much about the internals of tus-node-server to help you there. tus-node-server is writing to disk while it's receiving data, so both devices - network and disk - could be the bottleneck. Do you know that the network is fast enough and not throttling?

**Comment by djsg** [comment]
@Acconut  Thanks for your response. 
I suspect it is the network that are causing the issue. I just want to find out more information to confirm.
