### ISSUE TITLE
tried to make it available in Adonis.js but doesn't work

### ISSUE THREAD

**Issue by AndrewMeleka** [tus/tus-node-server#167]
here is my code it's create folder "files" but still cannot upload 
any help ??
it is possible to do that ?

```
const tus = require("tus-node-server");
const server = new tus.Server();
server.datastore = new tus.FileStore({
  path: "files",
});

Route.group(() => {
  Route.any("", server.handle.bind(server));
})
  .prefix("api/v1/uploads")
  .middleware("auth");
```

**Comment by Acconut** [comment]
What's exactly the problem? Do you get an error message?

**Comment by AndrewMeleka** [comment]
hey, thank you for reply,
here is the error 

Failed because: Error: tus: invalid or missing Location header, originated from request (response code: 204, response text: )

can fix when i add in CORS.js
exposeHeaders: ["Location", "Upload-Offset"]

but still doesn't upload my file :(

**Comment by Acconut** [comment]
What are you using as your endpoint URL? Should be something like localhost:8000/api/v1/uploads

**Comment by AndrewMeleka** [comment]
After many of tries and some of tricks i fixed & now working fine with Adonis.js, thank you :)

**Comment by kvz** [comment]
Please share your code snippets so that someone googling and finding this thread can save the time you spent fighting this! Good for karma :)
