### ISSUE TITLE
502 Bad Gateway in AWS

### ISSUE THREAD

**Issue by ReverseFlash28** [tus/tus-node-server#17]
I already upload it in AWS but i got an error 502 Bad Gateway

**Comment by makoy21** [comment]
@ReverseFlash28 
When uploading in AWS include the tus-server in your node-modules or if you use the eb deploy include in your gitigore this lines
!node_modules
node_modules/*
!node_modules/tus-server

**Comment by ReverseFlash28** [comment]
it works. thanks!

**Comment by Acconut** [comment]
Thank you, @makoy21, for providing your help! :)
