### ISSUE TITLE
How to Upload to DigitalOcean spaces using S3Store?

### ISSUE THREAD

**Issue by littleboy1103** [tus/tus-node-server#172]
I want my files to uploaded to DigitalOcean spaces. But I couldn't perform the action with S3Store.

Is there any way to do this? like adding endpoint or something. I tried to add endpoint and it didn't worked for me.

Sorry, If  I'm asked it in a wrong place...

**Comment by Acconut** [comment]
Options that are passed to the S3Store constructor are also passed to the AWS SDK (see https://github.com/tus/tus-node-server/blob/master/lib/stores/S3Store.js#L81). The AWS SDK usually has a setting to change the endpoint, so you should be able to set it up for DigitalOcean Spaces. Hope that helps :)

**Comment by littleboy1103** [comment]
> Options that are passed to the S3Store constructor are also passed to the AWS SDK (see https://github.com/tus/tus-node-server/blob/master/lib/stores/S3Store.js#L81). The AWS SDK usually has a setting to change the endpoint, so you should be able to set it up for DigitalOcean Spaces. Hope that helps :)

When I tried to add this to constructor...
`endpoint: '{region}.digitaloceanspaces.com'`

It shows another error..
`UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'UploadId' in params`

**Comment by Acconut** [comment]
That should not happen but I don't really know what the reason is. Maybe you can investigate on your own since I don't really have time available for this right now.

**Comment by littleboy1103** [comment]
> That should not happen but I don't really know what the reason is. Maybe you can investigate on your own since I don't really have time available for this right now.

Okay, Thanks for the reply...

**Comment by manelio** [comment]
Old issue, but someone could find this interesting:

Digital Ocean sends the upload id information as `upload-id` instead `upload_id`, so the `_getMetadata` method of `S3Store` returns an empty upload id.

I wrote my own patched S3Store:

```
    _getMetadata(file_id) {
        log(`[${file_id}] retrieving metadata`);

        if (this.cache[file_id] && this.cache[file_id].file) {
            log(`[${file_id}] metadata from cache`);

            return Promise.resolve(this.cache[file_id]);
        }

        log(`[${file_id}] metadata from s3`);

        return this.client
            .headObject({
                Bucket: this.bucket_name,
                Key: `${file_id}.info`,
            })
            .promise()
            .then((data) => {
                this.cache[file_id] = Object.assign({}, data.Metadata, {
                    file: JSON.parse(data.Metadata.file),

                    // Patch for Digital Ocean
                    upload_id: data.Metadata['upload-id'] || data.Metadata.upload_id
                });

                return this.cache[file_id];
            })
            .catch((err) => {
                throw err;
            });
    }
```

Is just one line and I *think* it's safe to be added to the repo.

**Comment by Murderlon** [comment]
@manelio good find! Are you willing to make a PR for it?

**Comment by manelio** [comment]
@Murderlon Sure! Done.

I'm not very used to GH pull requests and don't know if I've done it right.
