### ISSUE TITLE
11 high severity vulnerabilities

### ISSUE THREAD

**Issue by cekvenich2** [tus/tus-node-server#191]
Installing this via npm I get 11 high severity vulnerabilities warning in red.

**Comment by mitjap** [comment]
I checked on current master and got 1 waning. Which version do you use?
> 1 moderate severity vulnerability

Current published version (0.3.2) has lot more issues.
> 101 vulnerabilities (33 low, 25 moderate, 38 high, 5 critical)

**Comment by Murderlon** [comment]
Fixes in a07d57c33e5afcd40d1567e387decfba77bec78b and ce40ac2d4ef5f4489bcf09da693036b8bb999aea
