### ISSUE TITLE
False uploadUrl

### ISSUE THREAD

**Issue by irvanherz** [tus/tus-node-server#195]
I'm using tus-js-client. 
**https://development.interskill.id/backendv2/** is my API base base URL.
I don't really know what happened. But I got false upload URL from tus-node server.
![Screenshot from 2021-11-08 13-21-57](https://user-images.githubusercontent.com/12388998/140694346-99dfca59-a856-4af6-8462-0caeca2274c3.png)

**Comment by irvanherz** [comment]
> Do you use any reverse proxy or have express app mounted to `backendv2` subpath?

Yes, I am

**Comment by irvanherz** [comment]
By the way, I'm trying to implement optional baseUrl options for the TusServer class. Can I submit PR for this?
https://github.com/irvanherz/tus-node-server/commit/40c37bd68af17daeffd7d60fe995881babdf1bfd

**Comment by mitjap** [comment]
I am aware of this issue with reverse proxy. I'm thinking about implementing a URL generator parser that user could reimplement to fit their use case.
