### ISSUE TITLE
Publishing updated version of tus-node-server

### ISSUE THREAD

**Issue by vicky-g** [tus/tus-node-server#196]
hey! I noticed that you guys added a get handler in Server.js 
https://github.com/tus/tus-node-server/blob/e4ddd89d87e7838827c5f3b3478f2c7c08c10d4a/lib/Server.js#L13

along with some newer updates to this repo. the latest published version (v0.3.2) do not have some of these commits. will there be a published update soon? thank you!

**Comment by Acconut** [comment]
Thanks for letting us know! I just published https://github.com/tus/tus-node-server/releases/tag/v0.4.0 on NPM
