### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#22]
Allow configuration in the server construction.

[`Server#listen`](https://github.com/tus/tus-node-server/blob/447ca52ad25eb26acc3ffad702a64cf42fefd49c/lib/Server.js#L94-L97) should use [`https.createServer`](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener), with the config passed in the tus construction

```js
const tus = require('tus-node-server');
const config = {
    tls: {
        key: fs.readFileSync('/agent2-key.pem'),
        cert: fs.readFileSync('/agent2-cert.pem'),
    }
};
const tus_server = new tus.Server(config);
```

Also need to update [`PostHandler`](https://github.com/tus/tus-node-server/blob/447ca52ad25eb26acc3ffad702a64cf42fefd49c/lib/handlers/PostHandler.js#L37) to choose http|https based on the configuration

**Comment by jasonhenderson** [comment]
I did not see this implemented. Is this something we could try out?

**Comment by kvz** [comment]
Initially I wasn't an absolute 💯  on this for reasons mentioned in https://github.com/tus/tus-node-server/issues/13#issuecomment-158169623:

> Does it have to be baked into the server itself? e.g. if you'd use an ssl terminator like haproxy/stunnel/nginx, you could run the tus server as a nonprivileged user (port > 1024), and also when the next heartbleed surfaces, that damage will be limited to the terminator - vs potentially leaking more sensitive data out of the tus process.

That being said, I do also see the convenience this could offer. Not having deployed TLS in Node myself before, does anyone know how you'd make it open port 443 as a non-root user? Or is it required to do sth along the lines of a `setuid` to switch to a non-priviliged user, right after having accessed the keys and opened the port? If so, then I guess implementing this, would also require a configuration parameter for specifying which user/group to degrade to?

But as mentioned I'm a bit out of my comfort zone talking about this, so it's certainly possible Node.js has figured out a clever way to go about this already.

**Comment by jasonhenderson** [comment]
@kvz thanks for the reply. I will probably give the ssl terminator solution a try. Initially I had some reasons to avoid this approach, but after giving it some thought, it should work just fine.

**Comment by bhstahl** [comment]
Closing per conversation above
