### ISSUE TITLE
Allow for custom file names

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#25]
Implementations should be able to provide filename for `POST` requests, and only if it is not provided, it can default back to [`Uid`](https://github.com/tus/tus-node-server/blob/master/lib/models/Uid.js).

Thanks for the suggestion @js3692!

**Comment by js3692** [comment]
Great! I would love to help out with this one, if it wasn't already picked up.

My thoughts right now is to pass an options parameter to the `TusServer` instance:
```javascript
app.post('/api/videos/tus-upload', function(req, res) {
  server.handle(req, res, { filename: '50554d63-29bb-11e5-b345-feff819cdc9f' });
});
```
And either override the File id or instantiate with a file name in the POST handler:
```javascript
send(req, res, options) {
[...]
  if (options && options.filename) {
    file.id = options.filename;
  }

  OR

  // filename would be '50554d63-29bb-11e5-b345-feff819cdc9f'
  // When undefined the constructor would default it to Uid
  const file = new File(upload_length, upload_defer_length, filename);
[...]
}
```

@bhstahl What are your thoughts?

**Comment by bhstahl** [comment]
Sure! Feel free to open a PR from your fork.

While your suggestion works well for express, it doesn't really make sense for a standalone server that isn't planning on intercepting every request. 

 I wonder if it could be even simpler. You're going to have some sort of hashing function to generate the file name anyhow, right? What if `DataStore.create` takes the request instead of a `File`, then the DataStore decides the file name and creates the `File` itself. That way you provide the hashing function once and you're good to go:

```js
// Datastore.js
class DataStore {
    constructor(options) {
        this.generateFileName = options.namingFunction || Uid.rand;
    }

    create(req) {
        const file_name = this.generateFileName(req);
        //...
    }
}

// your_server_implementation.js
const fileNameFromUrl = (req) => {
    return req.url.replace(/\//g, '-');
}

server.datastore = new tus.FileStore({
    path: '/files',
    namingFunction: fileNameFromUrl
});

```

What do you think @js3692 ?

**Comment by js3692** [comment]
Thanks for the comments! I'll open a PR soon.

Yes, I think your suggestion makes better sense for standalone servers to take the hashing function. It could also allow express to flexibly attach the file name to `req.filename` for example and in the `namingFunction` just `return req.filename`.

I've implemented the `Datastore.create()` to take in req, decide the file name, and create `File`. Please let me know if there's anything to fix!

**Comment by bhstahl** [comment]
closed in https://github.com/tus/tus-node-server/pull/30

**Comment by avillarubia** [comment]
> Thanks for the comments! I'll open a PR soon.
> 
> Yes, I think your suggestion makes better sense for standalone servers to take the hashing function. It could also allow express to flexibly attach the file name to `req.filename` for example and in the `namingFunction` just `return req.filename`.
> 
> I've implemented the `Datastore.create()` to take in req, decide the file name, and create `File`. Please let me know what you think!

sorry but req.filename is undefined
