### ISSUE TITLE
handling of partial uploads without concatenation extension

### ISSUE THREAD

**Issue by mitjap** [tus/tus-node-server#259]
How should a server handle partial uploads? At the moment none of the data stores implement this extension and client can upload parts with `Upload-Concat: partial` header present, just to be disappointed at the end when concatenation fails with `Upload-Concat: final; ....`.

Should server throw error already on partial upload when `Upload-Concat` header is present to make it more obvious that this feature is not supported?

**Comment by Murderlon** [comment]
> Should the server implement some default handler which would immediately reject all request for unimplemented extensions rather to wait for random error to happen later?

I think it ties into your suggestion of not setting methods, like DELETE, if it isn't' supported. Although that would likely be a `405` (method not allowed), this would probably be a `501` (not implemented) with a helpful error message.

**Comment by mitjap** [comment]
I like the idea that extensions could be enabled/disabled with some configuration so you enable what you want. For that purpose I'd return `405` (method not allowed) if extension is not enabled or just not implemented.

**Comment by Acconut** [comment]
I think for the Concatenation extension it would make sense to check for the presence of the Upload-Concat header. If it is present and the data store does not support concatenation, the server should error out. I think a 400 Bad Request or 501 Not Implemented is an appropriate response for this situation. We cannot satisfy the upload according to the request from the client, so an error is the correct behaviour.
