### ISSUE TITLE
Custom file directories for FileStore

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#26]
`path` and `directory` don't have to be the [same thing](https://github.com/tus/tus-node-server/blob/master/lib/stores/FileStore.js#L23) and in many cases shouldn't.

FileStore construction should be:

```js
server.datastore = new tus.FileStore({
  directory: 'files/videos/user-uploads',
  path: '/api/videos/tus-upload'
});
```

Thanks for the suggestion @js3692!

**Comment by js3692** [comment]
You're welcome!

**Comment by bhstahl** [comment]
Oops this was done in the [initial commit](303e63115ae3b0413a974d4041e1d29c7f54facd), already supported :)

```js
this.directory = options.directory || options.path.replace(/^\//, '');
```
