### ISSUE TITLE
Please add upload validation feature

### ISSUE THREAD

**Issue by irvanherz** [tus/tus-node-server#263]
I need a way to validate files and JWT tokens to know which user did the upload. Also, the upload process started only if it passes user-defined validation. Maybe it can be implemented as a kind of middleware, extensions, or something. 
Its also important that tus events (EVENT_FILE_CREATED, EVENT_ENDPOINT_CREATED, EVENT_UPLOAD_COMPLETE) are extended with custom data based on that validation result.

**Comment by Murderlon** [comment]
For 1.0.0 of tus-node-server I want to align the events with [tusd](https://github.com/tus/tusd) and also introduce [blocking events](https://github.com/tus/tusd/blob/master/docs/hooks.md#blocking-hooks). This is what could be used for custom validation. It's on my todo list, so I'll close this for now. Feel free to continue the discussion.
