### ISSUE TITLE
GCSDataStore metadata get/set

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#27]
It appears you can't save metadata to an GCS object until the upload is complete. We need to figure out how to set/get `upload_length`, `upload_defer_length` from a GCS upload_id for `POST`/`HEAD` requests.

**Comment by js3692** [comment]
@bhstahl Would creating a JSON file (sort of like the configstore implementation in FileStore) and saving it like [this](https://github.com/js3692/tus-node-server-js/blob/master/lib/stores/GCSDataStore.js#L135) in GCS be a good alternative?

**Comment by bhstahl** [comment]
Unfortunately that wouldn't be scalable beyond a single instance, using the `FileStore`, keeping the files & the JSON file on that particular box. If you're running multiple instances, say behind a load balancer, that JSON file could be anywhere. Not to mention race conditions on read/writes. 

One of the many advantages of using an elastic file system like GCS or S3 (at least in the case of how we use them at Vimeo) is that the servers can be completely stateless, and the storage service gives us the shared file system.

**Comment by js3692** [comment]
Oh! Yes, I agree that beyond a single instance it will be impossible to keep track. What I meant was that since FileStore uses configstore to save the metadata as JSON locally, the GCSDataStore could do the same and save a separate JSON file to the cloud storage like FileStore does:
```
    // https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.33.0/storage/file?method=save
    saveMetadata(file_name, metadata) {
        return new Promise((resolve, reject) => {
            const file = this.bucket.file(`${file_name}.json`);
            file.save(JSON.stringify(metadata), (err) => {
                if (err) {
                    reject(err);
                }

                resolve();
            });
        });
    }

    // https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.33.0/storage/file?method=download
    getMetadata(file_name) {
        return new Promise((resolve, reject) => {
            const file = this.bucket.file(`${file_name}.json`);
            file.download((err, data) => {
                if (err) {
                    reject(err);
                }

                resolve(data);
            });
        });
    }
```

**Comment by bhstahl** [comment]
Well, the intentions are different when you choose a DataStore. Choosing the FileStore means you would have to only be running one instance per host. Every request to a host will come to the same machine, which has the same file directory and config store.

Choosing an elastic datastore, like GCS or S3, means you're not relying on anything to be on the server's machine. Say, for example, the load balancer routes the `POST` to one machine, and the `PATCH` to another machine. All persistence for GCSDataStore and S3DataStore should be in GCS and S3 respectively.

**Comment by js3692** [comment]
Thanks for explaining that! My point also was to persist everything on GCS (sorry if that wasn't clear) - when the POST request comes in with the metadata, the server will persist the data to GCS (see image below). This is an extra http cycle between the server and GCS, but I was wondering if it could be an alternative to the issue highlighted above.

<img width="1026" alt="screen shot 2016-05-22 at 1 44 47 pm" src="https://cloud.githubusercontent.com/assets/14022304/15455502/db3df21e-2023-11e6-981a-e9d9546ea71b.png">

**Comment by bhstahl** [comment]
Ahh i see what you were saying @js3692. We can store metadata on the objects, and I actually just got it working, so no need for an extra file to store json 😄
