### ISSUE TITLE
Release new patch version

### ISSUE THREAD

**Issue by Acconut** [tus/tus-node-server#273]
Since the last release (v0.7.0) there have been two fixes for the S3Store (see https://github.com/tus/tus-node-server/compare/v0.7.0...master). Would it be possible to release them soon as v0.7.1?

**Comment by Murderlon** [comment]
I think we're close to merging #186, afterwards I'll create a release.

**Comment by mitjap** [comment]
That would probably be 0.8.0 with breaking changes and possibly some new issues. I'd also recommend 0.7.1 with current changes.

**Comment by Murderlon** [comment]
Closed in ba0a7bd
