### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by Tronikelis** [tus/tus-node-server#290]
Hello, 
Awesome library btw and a quick question, why are these packages: `@google-cloud/storage` and `aws-sdk` not "peerDependencies" ?
If those packages are optional, then I think installing them is just extra bloat in the node_modules and wasted bandwith.  
With peer dependencies you need to install the packages listed above manually in your own project's package.json, so you install only what you need.

**Comment by Murderlon** [comment]
Hi! I think the better alternative to achieve the same is pulling out the stores as separate packages: #61. Work on tus-node-server 1.0.0 will start soon, which we'll likely include this. Closing this but feel free to continue the discussion here.
