### ISSUE TITLE
Bytes range in GET requests

### ISSUE THREAD

**Issue by piranna** [tus/tus-node-server#292]
When GETting a file, it's being fully returned. What I need is to get bytes ranges of the uploaded file, also before it's fully uploaded (i don't know size in advance). Are both things (get bytes ranges, and downloads before being fully uploaded) forbiden by TUS protocol, or are they missing features of this implementation? Would you accept a PR accepting both features?

**Comment by Acconut** [comment]
> Are both things (get bytes ranges, and downloads before being fully uploaded) forbiden by TUS protocol,

Both are neither forbidden nor required by tus. tus does not make any specification regarding GET requests. So tus-node-server is not offering these ATM.

> Would you accept a PR accepting both features?

That's best answered by @Murderlon :)

**Comment by piranna** [comment]
> Both are neither forbidden nor required by tus. tus does not make any specification regarding GET requests. So tus-node-server is not offering these ATM.

I have read some other issues (in particular in `tusd` repo) and this seems to be the case, that since TUS protocol is just only for uploads, it doesn't care at all for downloads, so yes, lack of both features is just an implementation detail, and nothing forbid adding them, or not, or doing it in a custom `GET` handler. I'm going to try this option first while getting an answer from @Murderlon :-)

**Comment by piranna** [comment]
I've look about adding a custom GET handler to don't need to patch source Code, and it's not possible, since paths and handlers are stored in a Map object, and I would need It to have support for path identifiers. How can I add support for It easily?

**Comment by Murderlon** [comment]
Hi, just for my understanding, you basically want to offset of a file in a GET request? Does something like this (pseudo code) work for you:

```js
const server = new Server();
server.datastore = new tus.FileStore({ path: '/files' });

server.get('/files/:id', (req, res) => {
  const offset = server.datastore.getOffset(req.params.id)
  res.writeHead(200);
  res.write(offset);
  res.end();
});
```

Although at this point you are basically recreating the already existing `HEAD` implementation, but perhaps you want additional things?

**Comment by piranna** [comment]
> Does something like this (pseudo code) work for you:

Almost. It allows me to get the `:id` parameter can help me, since I can identify the file I'm trying to get. In the long run, what I want is to also get the `range` header and return a fragment of that file.

**Comment by Murderlon** [comment]
> In the long run, what I want is to also get the `range` header and return a fragment of that file.

I see. If you are using filestore, I think this could be straightforward by doing a `fs.readFile` call for the `id` in the upload folder. Unfortunately, `getOffset` returns different things depending on the store. Consistency there is something I'll tackle for the 1.0.0 version. The S3 store does also return all the `parts` that are already uploaded, so technically that is the "fragment of that file". The GCS store does not.

**Comment by piranna** [comment]
> I think this could be straightforward by doing a `fs.readFile` call for the `id` in the upload folder.

Mostly yes, you just only need to provide the offset and length, fetch from the `range` header, and later return a `Content-Range` header back.

**Comment by Murderlon** [comment]
So what is still missing to make this work in a custom GET handler?

**Comment by piranna** [comment]
> So what is still missing to make this work in a custom GET handler?

To do it myself in a custom `GET` handler, and don't need to change the current behaviour for default handler (although I think it's the correct aproach...), I just only need to be able to have a `:fileId` parameter in the path, nothing else. I can take it from there.

**Comment by Murderlon** [comment]
Closing this as I think this can be solved with a custom GET handler

**Comment by piranna** [comment]
> Closing this as I think this can be solved with a custom GET handler

I've re-read the thread, and no, it's not possible with a custom `GET` handler with the current implementation of the module.

**Comment by piranna** [comment]
I need both the file ID and the byterange header.
