### ISSUE TITLE
It is possible to specify a custom S3 path? (DigitalOcean Spaces)

### ISSUE THREAD

**Issue by joshmotion** [tus/tus-node-server#295]
hey there, I'm wanting to use DigitalOcean spaces which supports uploading data via S3. Is it possible change the S3 destination endpoint to something other than GCP or AWS? It seems ``tus.S3Store`` is locked to AWS with no way to change the endpoint. Thanks.

**Comment by mitjap** [comment]
All options passed to S3Store are passed to AWS S3 client constructor. Based on Digital Ocean example you need to pass `endpoint` parameter.

https://github.com/tus/tus-node-server/blob/e7669c7434645095b42b346886e41ad1c8ac4f79/lib/stores/S3Store.js#L53

This should work:
```
new S3Store({
    bucket: "BUCKET_NAME"
    endpoint: "https://nyc3.digitaloceanspaces.com",
    region: "us-east-1", 
    credentials: {
      accessKeyId: "C58A976M583E23R1O00N",
      secretAccessKey: process.env.SPACES_SECRET
    }
})
```

**Comment by joshmotion** [comment]
thakns
