### ISSUE TITLE
GCS and S3 bucket inexistence handling

### ISSUE THREAD

**Issue by mitjap** [tus/tus-node-server#300]
I'm opening a discussion that started in #299  about bucket existence checking. GCSDataStore does this asynchronously in constructor which by definition can not be async and any proper handling would cause race condition. If there is any error with this check or bucket does not exists all thrown errors are unhandled and usually causes application to exit with error code (crash).  
https://github.com/tus/tus-node-server/blob/9eeb26c40042f1f95ccba71f0ff51f792ca0c6ac/lib/stores/GCSDataStore.js#L47

S3Store handles bucket existence when uploading a file and in case of an error signals this in response with status code 500.
https://github.com/tus/tus-node-server/blob/9eeb26c40042f1f95ccba71f0ff51f792ca0c6ac/lib/stores/S3Store.js#L88

**Comment by Murderlon** [comment]
I think it makes most sense to align with the S3 store here. During the initial POST it seems reasonable to find out at that time the bucket doesn't exist.

**Comment by mitjap** [comment]
`POST` is optional extension and might not be used. 

I recommend testing at startup and save result as a promise which is always evaluated on every request. If initial test failed, all subsequest requests will fail. Another option is to just ignore this check (we can still print a warning to logs) and let it error on later requests. For example GCS reports that IAM does not have sufficient access if bucket does not exists when creating new object (on upload creation).

**Comment by Murderlon** [comment]
I mean the initial POST _to S3_ not to the tus server, which is how it currently works for the S3 store, and apply that to GCS too. The way I see it, is that setting up a bucket is a prerequisite and we don't have to go too fancy.

**Comment by Murderlon** [comment]
AFAIK this check doesn't explicitly exist in tusd, it just fails the creating request to S3 for instance. Do we really want to separate these failures? If you can't recover from it, and creating a bucket is a prerequisite, why do we need it?

**Comment by Acconut** [comment]
Yes, tusd does not check the existence of buckets. It is not because I am opposed to the idea, but that I have not seen it to be big problem for users, so it is not a high priority.

If you add such a check, I would recommend to just check one upon startup and not very every upload. That seems just like a wasted request for every upload to me. Instead of putting it inside the constructor, stores could have a `checkSetup` method, which users can call to validate the setup (e.g. the bucket configuration).
