### ISSUE TITLE
Amazon S3

### ISSUE THREAD

**Issue by habibErfani** [tus/tus-node-server#312]
Hello, 

Hope you are going well. 

I wanted to know if it’s possible to use an S3 that is not on Amazon with this code. For exemple Scaleway. 

Waiting for your response,

Sincerely,

**Comment by Murderlon** [comment]
Hi, as long as it's S3-compatible it should work, such as for Digital Ocean Spaces: https://github.com/tus/tus-node-server/issues/295.

**Comment by habibErfani** [comment]
Thank you very much,

**Comment by mitjap** [comment]
I use it with scaleway and it works.
