### ISSUE TITLE
Save the offset in the File model and datastores instead of size

### ISSUE THREAD

**Issue by Murderlon** [tus/tus-node-server#321]
I've always found it a bit confusing to have both `upload_length` and `size`. AFAIK if we save the `offset` instead of the `size` we can still do the same safety checks we use the `size` for.

It is currently used in these places:

https://github.com/tus/tus-node-server/blob/a714b3f60de1027cd635d7713d10c81675adc49b/lib/handlers/GetHandler.ts#L43-L48

https://github.com/tus/tus-node-server/blob/a714b3f60de1027cd635d7713d10c81675adc49b/lib/handlers/PatchHandler.ts#L36-L42

https://github.com/tus/tus-node-server/blob/a714b3f60de1027cd635d7713d10c81675adc49b/lib/handlers/PatchHandler.ts#L57-L59

https://github.com/tus/tus-node-server/blob/a714b3f60de1027cd635d7713d10c81675adc49b/lib/handlers/HeadHandler.ts#L21

cc @Acconut @mitjap

**Comment by mitjap** [comment]
I don't fully understand what it is you are proposing here. Do you want to rename `size` to `offset`?

**Comment by Acconut** [comment]
I am also a bit confused as @mitjap. But I am on board if it is about renaming the `size` property while keeping `upload_length`.

**Comment by Murderlon** [comment]
Excusez-moi, I was looking at both tusd and tus-node codebases at once and saw a different pattern, but the same things happen, only the naming is different. Ignore this.
