### ISSUE TITLE
File is never written.

### ISSUE THREAD

**Issue by sirakoff** [tus/tus-node-server#33]
File is never written in a vagrant box with shared folder.

**Comment by sirakoff** [comment]
Sorry, it had something to do with nginx. Nginx is sending a `413 Request Entity Too Large response` at the very end of the upload. I have tried adjusting `client_max_body_size` in nginx.conf but its still happening.

**Comment by kvz** [comment]
You will also have to use nginx 1.8 Or later and turn on request buffering or it will buffer the entire upload before handing it over to tusd which is very inefficient. If after this you still have problems you might want to consult the nginx community, or enable our concat extension which splits up large files into smaller ones, circumventing any limit a proxy might pose on file sizes. @acconut maybe we can add sth like this to the best practices document as well?

**Comment by sirakoff** [comment]
It worked after upgrading nginx to the latest version. Thanks!

**Comment by bhstahl** [comment]
👍

**Comment by sirakoff** [comment]
Pausing and resuming causes the upload to start all over.

**Comment by kvz** [comment]
Did you turn request buffering off yet?

**Comment by sirakoff** [comment]
Yes, `proxy_request_buffering off;` right?

**Comment by kvz** [comment]
Yes, there's a few things you want to make sure of such as

```bash
proxy_request_buffering  off;
proxy_buffering          off;
proxy_http_version       1.1;
proxy_set_header         Upgrade $http_upgrade;
proxy_set_header         Connection "upgrade";
client_max_body_size     0;
```
