### ISSUE TITLE
endpoint url

### ISSUE THREAD

**Issue by rezasafaei70** [tus/tus-node-server#334]
Where and how should I enter the endpoint?
endpoint=https://s3.Ar................
```
= new tus.S3Store({
    bucket: 'bucket-name',
    accessKeyId: 'access-key-id',
    secretAccessKey: 'secret-access-key',
    region: 'eu-west-1',
    partSize: 8 * 1024 * 1024, // each uploaded part will have ~8MB,
});
```

**Comment by Murderlon** [comment]
It's not required for it to work but all options are passed to the `aws.S3` directly so you can pass it. This should be better reflected in the docs and types. Thanks for the reminder. Will do it for #309
