### ISSUE TITLE
GCSDataStore can't return 410 Gone when appropriate

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#36]
Once a file is deleted from GCS, there's currently knowing it once existed. Therefore, `GCSDataStore.getOffset()` can't return `ERRORS.FILE_NO_LONGER_EXISTS` when appropriate.

**Comment by mitjap** [comment]
What would be the best solution for this? Same issues is with any datastore that has metadata embedded. Should we also implement some kind of metadata store? For example I image redis could be faster metadata store that reading from GCS object, or maybe even in-memory if persistence is not a requirement.

**Comment by Acconut** [comment]
I don't think a solution is really needed. The tus specification does not require a 410 to be returned but allows servers to do so if they somehow know that such an upload existed earlier. Implementing a separate meta data store just for this purpose seems superfluous to me.

**Comment by mitjap** [comment]
I agree with @Acconut. Closing this issue as it does not need a fix.

**Comment by Acconut** [comment]
Agreed!
