### ISSUE TITLE
@tus/server was not found at NPM

### ISSUE THREAD

**Issue by ilomon10** [tus/tus-node-server#361]
I'm just come from [this](https://github.com/tus/tus-node-server#quick-start) tutorial, then install this `@tus/server` but it was not found on NPM server.

**Comment by Murderlon** [comment]
Yes sorry, I merged the `1.x` branch where all the work happened into `main`, ready to publish. Then I found out I didn't have publish rights yet.. Will publish in one hour!

**Comment by ilomon10** [comment]
Okey thankyou.
