### ISSUE TITLE
@tus/server and next.js

### ISSUE THREAD

**Issue by toddgeist** [tus/tus-node-server#362]
I have been trying to get Tus Server to work with Next.js api routes.  So far, I haven't had any luck. My latest attempt seems to get close. It creates a file on the disk, and sends patch requests to the server that is received with a 204 response, but nothing appears in the file. It just keeps trying the patch over and over again.

I created a repo that has it set up the way I think it should work. It has the server attached at `/api/upload`, and Uppy Dashboard at `/`

https://github.com/toddgeist/next-tus

Is there some configuration I missed?

Thank you

**Comment by toddgeist** [comment]
(btw) if we can get this to work, it would make a nice example. I'd be happy to make a P/R for it.

**Comment by Murderlon** [comment]
Hi, on a quick glance I'm not sure what's wrong either. I don't know what `[[...upload]]` does as a file system route in Next.js, perhaps that's not ideal or a mismatch with the configured `/api/upload`?

**Comment by toddgeist** [comment]
I made some progress.  I update the repo, and the code there can no successfully upload a file. YAY.  

The FileStore didn't rename the file, but that may be just be some config I haven't done yet.  They key is you have to tell next to not parse the body for that API Route.

https://github.com/toddgeist/next-tus/blob/main/pages/api/upload/%5B%5B...slug%5D%5D.ts

```
export const config = {
  api: {
    bodyParser: false,
  },
};
```
Now I just need to get the file to get named correctly

**Comment by toddgeist** [comment]
Ok I have this working. The repo above has a working example.  If it looks good to you I can make a pull request.

Thanks :-)

**Comment by toddgeist** [comment]
Ah, I didn't understand the naming function. That makes sense.  I'll get that into the PR.

Thanks :-)

**Comment by toddgeist** [comment]
PR  - https://github.com/tus/tus-node-server/pull/364
