### ISSUE TITLE
respectForwardedHeaders only recognizes Capitalized forms of the headers

### ISSUE THREAD

**Issue by toddgeist** [tus/tus-node-server#365]
I am running a next.js app behind a proxy. Next sends the headers through to the tus handler as lower case.  The BaseHandler.ts file only looks at `req.headers['X-Forwarded-Proto']`.  

```js
const forwardHost = req.headers['X-Forwarded-Host'];
const forwardProto = req.headers['X-Forwarded-Proto'];
```

This solved the problem for me.
```js
const forwardHost = req.headers['x-forwarded-host'] || req.headers['X-Forwarded-Host'];
const forwardProto = req.headers['x-forwarded-proto'] || req.headers['X-Forwarded-Proto'];
```

If this seems like the right approach I can submit a PR.

Thanks :-)

Todd

**Comment by Murderlon** [comment]
Good catch! I think we only need lowercase actually, as all references with `req.headers` in the server only use lowercase at the moment. 

PRs welcome! I see they haven't been added yet to [`constants`](https://github.com/tus/tus-node-server/blob/main/packages/server/src/constants.ts#L3) either.

**Comment by toddgeist** [comment]
oh wow I was just about to start a PR on this. Thanks !
