### ISSUE TITLE
Proxy subfolder gets lost when generating the uploadUrl

### ISSUE THREAD

**Issue by toddgeist** [tus/tus-node-server#366]
For this product we are working on we are installing a next.js app into preexisting web servers and using a Reverse Proxy configs to mount the next app under a subfolder.

`https://proxy.server.com/ourapp/`

Where our app responds to any calls to `/ourapp/*`

I haven't been able to get that subfolder added to the uploadUrl that gets returned in the Location header of the POST.  Using the `path` option doesn't work.  Or rather I can add the subfolder to the path option and the right URL comes back in Location, but then the PATCH call then fails with a 404, because BaseHandler.generateFieldFromRequest(), can't find the file.

https://github.com/tus/tus-node-server/blob/09a8e38f52e4bb7ff05e7802a824cb6cc6b3e09d/packages/server/src/handlers/BaseHandler.ts#L66-L77

I hacked in a working solution by adding another Server Option `proxySubFolder`, and then using it BaseHandler.generateUrl()

```ts
const proxySubFolder = this.options.proxySubFolder || '';
return `${proto}://${host}${proxySubFolder}${baseUrl}${path}/${id}`;
```

Is there a better way to do this?  Did I miss something?

Thanks 👻

**Comment by Murderlon** [comment]
@toddgeist can you check if that PR works for you?

**Comment by Murderlon** [comment]
Published: https://github.com/tus/tus-node-server/releases/tag/%40tus%2Fserver%401.0.0-beta.2
