### ISSUE TITLE
CORS Enable Headers

### ISSUE THREAD

**Issue by feluna** [tus/tus-node-server#38]
Hi, my implementation was failing due to missing headers in response. File uploads were not resuming. I inspected the http://tus.io/demo.html network requests and noticed this header, which was missing in my node server's responses:

`'Access-Control-Expose-Headers' : 'Upload-Offset, Location, Upload-Length, Tus-Version, Tus-Resumable, Tus-Max-Size, Tus-Extension, Upload-Metadata'`

I examined the node.js library code a little bit, and discovered that on Server.js file you are controlling CORS with the following lines : 

```
if (req.headers.origin) {
     res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
}
```

I believe it should also set the "Access-Control-Expose-Headers" header too. So i changed to following piece of code and it worked :

```
if (req.headers.origin) {
     res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
     res.setHeader('Access-Control-Expose-Headers' , 'Upload-Offset, Location, Upload-Length, Tus-Version, Tus-Resumable, Tus-Max-Size, Tus-Extension, Upload-Metadata');
}
```

Is there a better way to achieve CORS, or is this the way to do it? Thank you.

**Comment by bhstahl** [comment]
Ah yes. A fix could be similar to `'Access-Control-Allow-Headers'` in the [OptionsHandler.js](https://github.com/tus/tus-node-server/blob/8fd4f5b8cd7b4c7be73eeb9caaf6708abcf4cf33/lib/handlers/OptionsHandler.js#L22).

I can submit a patch, unless you have a pull request ready to go?

Thanks @feluna !

**Comment by feluna** [comment]
You can submit a patch, thank you as well.

**Comment by bhstahl** [comment]
@feluna if you update to [tus-node-server@0.1.1](https://www.npmjs.com/package/tus-node-server) you should be good to go 👍

**Comment by krampampuli** [comment]
Hi, I'm using 0.1.1, but still had to include the extra line from the original post to make the missing header part appear and the file uploads resume.

**Comment by bhstahl** [comment]
@krampampuli I realized a case where it wouldn't be added to the `HEAD` request, which is fixed in [tus-node-server@0.1.2](https://www.npmjs.com/package/tus-node-server). Let me know if you have any trouble after upgrading!

**Comment by krampampuli** [comment]
After upgrade it gives "405 Method Not Allowed: The requested method PATCH is not allowed for the URL /null." 

Exposed headers seem to miss Location, i.e., it should be added to const HEADERS in constants.js

Thanks!

**Comment by bhstahl** [comment]
@krampampuli thanks for your help. `Location` is added in [tus-node-server@0.1.3](https://www.npmjs.com/package/tus-node-server).

Not sure I'm following how `PATCH` isn't allowed, since it is included in the `Access-Control-Allow-Methods` of `OPTIONS` request. Would you mind opening up a separate ticket with detailed steps to replicate?

**Comment by krampampuli** [comment]
Since there was no Location info, the URL for PATCH was null. That was the actual error.
Now everything seems to be OK, thank you!
