### ISSUE TITLE
FileStore: Async configstore to support databases (e.g. Redis) as configstore

### ISSUE THREAD

**Issue by marlon360** [tus/tus-node-server#384]
At the moment the configstore implementation of the FileStore has to be synchronous. 
This makes it only possible to use an in-memory or file-based store.

To support databases like redis for storing the configuration the configstore needs to async.

@samal-rasmussen mentioned this already here: https://github.com/tus/tus-node-server/pull/206#issuecomment-1049682476

**Comment by Murderlon** [comment]
I agree. I'm currently on holiday until 22 February, will look into it when I'm back. We should tackle this before we go from beta into the stable release.
