### ISSUE TITLE
unable to start, syntax

### ISSUE THREAD

**Issue by aburger** [tus/tus-node-server#39]
hi there,

i am new with node.js as with tus, i tried to start an example und run in one problem after the other. first your examples are with const, but the code i got wit npm install uses strict and so const does not work. there are even module in the installbase with const.

then:
npm run example

> tus-node-server@0.1.0 example /usr/local/node_modules/tus-node-server
> nodemon example/server.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node example/server.js`

/usr/local/node_modules/tus-node-server/index.js:9
    Server,
          ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/node_modules/tus-node-server/example/server.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[nodemon] app crashed - waiting for file changes before starting...

where inds.js contains:
module.exports = {
    Server,
    DataStore,
    FileStore,
    GCSDataStore,
};

....

**Comment by Acconut** [comment]
It seems like you are using an older version of Node.js which does not support the newer ES2016 syntax. We recommend using, at least, Node.js 4.2.X for full support. Please try this approach.

**Comment by aburger** [comment]
Am 27.07.2016 um 16:20 schrieb Marius:
> It seems like you are using an older version of Node.js which does not support the newer ES2016 syntax. We recommend using, at least, Node.js 4.2.X for full support. Please try this approach.

thanks.
is there a way to use the distros npm but with newer source?

best regards
andreas


--

**Comment by Acconut** [comment]
It's generally recommended to use a version manager for Node, such as nvm (https://github.com/creationix/nvm) or n (https://github.com/tj/n).

**Comment by aburger** [comment]
it works with the new version via git, thanks
