### ISSUE TITLE
Use modularized AWS SDK v3 to reduce size 

### ISSUE THREAD

**Issue by gthau** [tus/tus-node-server#394]
[Since version 3, AWS SDK is modularized](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/). This allows to use only the subset of functionality required from the SDK and reduce the size of node_modules.
This is important in order to reduce the overall size of docker images: in my specific case, the main contributor to the final docker image size is the aws-sdk folder in node_modules (116MB), most of which comes from unneeded `.d.ts` and `.json` files related to many AWS services which are not used in tus-node-server.

**Comment by mitjap** [comment]
I agree with you. 

Something in this direction is already in progress with https://github.com/tus/tus-node-server/pull/388 but for GCS (S3 is next). AWS SDK or any part of it will be peer dependency and will allow user to install any version or package that provides compatible interface. Will keep in mind to use `@aws-sdk/client-s3` as peer dependency for S3.

**Comment by m4xleb** [comment]
> I agree with you.
> 
> Something in this direction is already in progress with #388 but for GCS (S3 is next). AWS SDK or any part of it will be peer dependency and will allow user to install any version or package that provides compatible interface. Will keep in mind to use `@aws-sdk/client-s3` as peer dependency for S3.

I was just curious if it was still planned to integrate `@aws-sdk/client-s3` as the actual SDK is trowing an error ever time we start the service 

```console
(node:16467) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023. Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use `node --trace-warnings ...` to show where the warning was created)
```

Thanks!

**Comment by Murderlon** [comment]
Yes I still want to tackle this :)
