### ISSUE TITLE
Any of you have a sample with as datastore PostgreSQL?

### ISSUE THREAD

**Issue by sneko** [tus/tus-node-server#395]
Hi,

I used in the past Tus+Uppy to store files into a S3 bucket but to simplify the stack for a new project I would like to use my PostgreSQL (and its `bytea` type).

Are you aware of a `datastore` or `configstore` out of the box?

Thank you,

EDIT: an adaptation with another RDBMS (MySQL...) would be great too since easily customizable...

**Comment by mitjap** [comment]
There are no official datastores of this kind you can use out of the box. I'd recommend you to used `FileStore` and listen for `EVENT_UPLOAD_COMPLETE` event and then move the file to database.

**Comment by sneko** [comment]
@mitjap yeah I thought about this since using `bytea` does not handle streaming.

Will wait a bit before closing to get other thoughts.

Thank you :)

**Comment by mitjap** [comment]
PostgreSQL also support Large Objects. You could use this to store your files. Library [pg-large-object](https://www.npmjs.com/package/pg-large-object) implements streams around this functionality. As such it might be possible to implement datastore that would write directly to the database.

**Comment by sneko** [comment]
I went with `Filestore` to not overcomplicate my issue, thank you for your answer!
