### ISSUE TITLE
any way to attach custom payload after upload finished

### ISSUE THREAD

**Issue by primemb** [tus/tus-node-server#399]
I want to send some extra json information after upload finished i tried to do it in `onUploadFinish` but seems i cant change body inside of it ,
so is there any way to do that or am i miss something about `onUploadFinish`

**Comment by Murderlon** [comment]
You could put stringified JSON inside the upload metadata, but we currently do not allow to alter it inside hooks. Any chance you can attach the metadata from the client?

**Comment by primemb** [comment]
i think I have explained badly let me show my code;  right now on `onUploadFinish` i do some validation to make sure the file ext is correct, and also I save some information about files in the database i want if upload was fine send some extra information inside of body of response like this : 


```
onUploadFinish: async (req, res, upload) => {
    try {
      const { fileTypeFromFile } = await import("file-type");
      const type = await fileTypeFromFile(
        `${process.cwd()}/files/${upload.id}`
      );
      const fileExt = upload.id.split(".")[1];

      if (fileExt !== type?.ext) {
        await prisma.file.delete({ where: { file_unique_name: upload.id } });
        throw {
          body: "not valid file",
          status_code: 400,
        };
      }
    } catch (error) {
      loger.fatal(error);
      await unlink(`${process.cwd()}/files/${upload.id}`);
      throw error;
    }
    // here instead of returning the response i want add some json payload to the response body like
    // const file=await prisma.findOne({where: {file_unique_name: upload.id}})
    // res.json({fileId: file.id })
    return res;
  },
```
i am not sure if this possible but it would nice if we can do that

**Comment by Murderlon** [comment]
I understand now, thanks. The thing is, except when using the `creation-with-upload` extension (upload in `POST` instead of `PATCH`), you can't add a body because the `PATCH` always returns `204` which can never contain a body. For instance, from the Node.js docs:

> In the node:http module, the response body is omitted when the request is a HEAD request. Similarly, the 204 and 304 responses must not include a message body.

And the tus spec:

> The Server MUST acknowledge successful PATCH requests with the 204 No Content status.

Since the hook is potentially called in `PATCH` or `POST`, we can't do this.
