### ISSUE TITLE
hook when file uploaded

### ISSUE THREAD

**Issue by cometta** [tus/tus-node-server#40]
anyway to do a callback after a file is completed uploaded ? let say there is a need to write a record to database once file is successfully uploaded

**Comment by bhstahl** [comment]
Absolutely @cometta. Its on my list to add something similar to [tusd's hooks](https://github.com/tus/tusd/blob/master/.hooks/post-finish). A node EventEmitter style implementation could be:

```js
const server = new tus.Server();

server.on('upload_complete', (file) => {
    console.log(`New file uploaded to ${file.location}`);
});
```
Very open to you thoughts though, and PR's more than welcome!

**Comment by charleston10** [comment]
I also need

**Comment by bhstahl** [comment]
@cometta @charleston10 [Event hooks](https://github.com/tus/tus-node-server#event-hooks) have been added in [tus-node-server@0.2.0](https://www.npmjs.com/package/tus-node-server)!

**Comment by cometta** [comment]
Hello @bhstahl ,
 How to get event.file.upload_length  and event.file.upload_metadata  ? I can't get those value from event .

**Comment by bhstahl** [comment]
@cometta for which event and datastore? Can you open a separate issue detailing the steps to  replicate your outcome? 

Also, feel free to fork this repo, work on a fix  and submit a PR if you know what's happening!
