### ISSUE TITLE
An option (hook) to validate upload termination, similar to upload creation.

### ISSUE THREAD

**Issue by naumf** [tus/tus-node-server#400]
I want to ask if it's possible to add a hook (i.e. `options.onUploadTerminate`)  that will be invoked from the delete handler, in order to validate an upload termination request for v1? An `upload-metadata` header would have to be present as well.

Context: On upload creation, we can use `options.onUploadCreate` to validate the metadata, but there is no such an option for upload termination and also the metadata isn't passed to DELETE requests. Uppy doesn't send the metadata on upload abort and I didn't found an option the metadata with the tus-js-client as well (there is no such an option under tus.Upload.terminate). EDIT: Maybe metadata can be fetched from the store with an additional public method like the private method `getMetadata` in @tus/s3-store?

I already solved this on app level by integration of the tus-node-server with fastify and on client side by extending the tus-js-client, but wanted to ask if there is a proper way to do this, instead of the dirty one.

Thanks in advance and thanks for this amazing project.

**Comment by Murderlon** [comment]
Hi, I could be open to adding such a hook but I don't see the value yet. According to the protocol spec the `Upload-Metadata` isn't sent along (but it doesn't forbid it either). Practically this means that all clients won't send it, and therefor you won't be able to validate it.
