### ISSUE TITLE
Add support for lockers, including a distributed lock

### ISSUE THREAD

**Issue by fenos** [tus/tus-node-server#408]
The protocol [states](https://tus.io/faq.html#how-do-i-scale-tus) that: 

In order to horizontally scale a tus server there should be locks in place during the time the server interacts with the remote storage (s3 for example)

Does tus-node-server already solve this issue in some way? 
If not, do we need to implement an interface to add these custom locks?

Thanks!

**Comment by Murderlon** [comment]
Hi, there is no distributed lock so you probably would have to settle for sticky sessions when you scale. I'm willing to look into it but don't except it soon :)

**Comment by Acconut** [comment]
Distributed locking is definitely something that we should also explore in tusd. It's one of the things that users are most confused/concerned about, I guess.

**Comment by Murderlon** [comment]
I have a working distributed lock for tusd locally which I could upstream at some point.

**Comment by Acconut** [comment]
Amazing, feel free to PR to tusd!
