### ISSUE TITLE
Server crashes when killing client upload - S3 Store

### ISSUE THREAD

**Issue by fenos** [tus/tus-node-server#409]
I created a simple script to upload a file with the TUS js client to the tus-node-server (with fastify) 

When I lunch the client upload script and kill it (CTRL + C) after a few chunks have been uploaded, the server crashes with the following error:

```
tus-node-server [PatchHandler] Error: aborted
    at connResetException (node:internal/errors:717:14)
    at abortIncoming (node:_http_server:750:17)
    at socketOnClose (node:_http_server:744:3)
    at Socket.emit (node:events:524:35)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:316:12) {
  code: 'ECONNRESET'
} +7s

[Error: ENOENT: no such file or directory, lstat '/var/folders/r4/m30b545s1q93w60kgjk5lym00000gn/T/pfoNhWXgiL-0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/var/folders/r4/m30b545s1q93w60kgjk5lym00000gn/T/pfoNhWXgiL-0'
}
```

Once this error happens the only way to recover is to restart the server

**Comment by Murderlon** [comment]
That definitely shouldn't happen! I'll try to reproduce when I have time.

**Comment by fenos** [comment]
@Murderlon I figured the problem was just a typo on a catch statement. 

I've raised a PR to fix this #410

**Comment by josephrony277** [comment]
I'm trying to upload a file to S3 and getting the same exception after a few patch requests are sent to the server. I'm using the beta version that has the fix for the same error, but the issue still exists.

**Comment by Murderlon** [comment]
Can you upgrade to latest? There is a stable release after the beta. If it still persists, please open a new issue with as much information as possible.
