### ISSUE TITLE
HeadHandler missing Access-Control-Expose-Headers header

### ISSUE THREAD

**Issue by davidgourde** [tus/tus-node-server#42]
I start uploading a large file of 1GB and let it upload around halfway before closing the tab (Chrome). I open the page again and start to upload the same file. I always receive this message: 
```
Failed because: Error: tus: invalid or missing offset value
Do you want to retry?
```
The error in the console is:
`upload.js:257 Refused to get unsafe header "Upload-Offset"xhr.onload @ upload.js:257`

I am using tus-js-client to test this (the demo) and it works perfectly fine with tusd (in Go). This problem only occurs with tus-node-server.

My server is only a copy paste of the Quick Start code provided in the README under "Build a standalone server".

Uploading files works fine too, but never resumes correctly.

**Comment by bhstahl** [comment]
Whoops, that's what you get for building it by making requests from bash instead of a browser. The `HEAD` responses are missing the [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers) to whitelist the `Upload-Offset` header. Will add it!

**Comment by davidgourde** [comment]
I am unsure that this is the problem. The response for `HEAD `is 
```
Request Method:HEAD
Status Code:200 OK
```
but the response for `OPTIONS `is:
```
Request URL:http://127.0.0.1:1080/files/a27c859a376f927a51c47c5afc46d6bb
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:127.0.0.1:1080
```

And I see that in the response headers:
```
Access-Control-Allow-Headers:Upload-Offset, Upload-Length, Upload-Defer-Length, Upload-Metadata, X-Requested-With, Tus-Version, Tus-Resumable, Tus-Extension, Tus-Max-Size, Content-Type, X-HTTP-Method-Override
Access-Control-Allow-Methods:POST, HEAD, PATCH, OPTIONS
Access-Control-Allow-Origin:http://localhost:8080
Access-Control-Expose-Headers:Upload-Offset, Location, Upload-Length, Tus-Version, Tus-Resumable, Tus-Max-Size, Tus-Extension, Upload-Metadata
```
`Upload-Offset` is in the list. Unless I am not analyzing the problem correctly (I'm new to all of this).

**Comment by bhstahl** [comment]
Added in e38cb91e1556d4ee1e5a756a8780d84fc4b1b824. @davidgourde if you update to [tus-node-server@0.1.2](https://www.npmjs.com/package/tus-node-server) you should be good to go!

**Comment by davidgourde** [comment]
I suppose there are other missing Access-Control-Expose-Headers, as I now get this message when resuming an upload with `tus-js-client`: 
```
upload.js:286 HEAD http://localhost:8080/demo/null 404 (Not Found)_resumeUpload @ upload.js:286start @ upload.js:109(anonymous function) @ demo.js:82
upload.js:206 Refused to get unsafe header "Location"
```
