### ISSUE TITLE
Sending extra data with the response

### ISSUE THREAD

**Issue by Pitu** [tus/tus-node-server#422]
What's the best way to append some data to the response sent to the user once an upload finishes?
I'd like to append extra data to the response sent to the user on `onUploadFinish` but I'm not sure how to do so. I'm using Uppy core with TUS as the uploader and everything I tried so far to append data to the body has been unsuccessful.

Any tips?

**Comment by Murderlon** [comment]
Hi, could you be more specific? Do you mean headers? Alter the body of the request?

**Comment by primemb** [comment]
I think it's really needed too right now after the upload is finished on the front side how we should pass front some data to continue the chain of progress? for example, imagine having a website for transcoding movies when a user upload file i want to return back file id which is stored in the database so it can continue the chain of progress. i think must add a way to pass some data after the upload is finished the front

**Comment by Murderlon** [comment]
There are currently discussions in tusd for a similar feature, being able to change the metadata: https://github.com/tus/tusd/pull/814. Would be nice to align on a solution together with tusd.

**Comment by primemb** [comment]
that topic about changing the metadata header right now in `onUploadFinish` if we throw some error we can see it on the body of the request but there is no way to return a normal response in the body, is it not possible to just can return normal json so the front application can get it inside of the body?

**Comment by ggagosh** [comment]
Hey, is this feature already implemented or there is a way (I can't find it) to add some meta information to the `onUploadFinish` response? 🤔

**Comment by Pitu** [comment]
@ggagosh I closed it since I moved away from tus to something that better fits my needs

**Comment by Murderlon** [comment]
I still want to implement this for the `onUploadCreate` hook, similar to this PR: https://github.com/tus/tusd/pull/962.

I'm not sure yet what we can/want to allow for `onUploadFinish`.

**Comment by ggagosh** [comment]
@Murderlon but why? For example, when `onUploadFinish` is triggered, I get the `Upload` object and create db `File`. I want to return this file object for the client application. 

As I mention I set the custom header and return created `File` id, but it's nice if there is possibility to return some custom response

**Comment by Murderlon** [comment]
At the time of `onUploadFinish`, the upload has already been written to the store, so there is no point in allowing to modify the passed upload. As for the response, you're already able to do `res.setHeader()`, what more would you want to do and why?

**Comment by sammibajrami** [comment]
Hi, I'll just interject to give my answer to your question @Murderlon, which is that I want to be able to add some info that comes from the server to the metadata-object that the server returns to the client.
I don't want to make any changes to the uploaded file.

Like you said I could simply send the additional data along as a response-header but like @ggagosh said that feels a bit hacky
