### ISSUE TITLE
Missing Access-Control-Expose-Headers header for "Location"

### ISSUE THREAD

**Issue by davidgourde** [tus/tus-node-server#43]
I start uploading a large file of 1GB and let it upload around halfway before closing the tab (Chrome). I open the page again and start to upload the same file. I always receive this message:
```
upload.js:286 HEAD http://localhost:8080/demo/null 404 (Not Found)_resumeUpload @ upload.js:286start @ upload.js:109(anonymous function) @ demo.js:82
upload.js:206 Refused to get unsafe header "Location"
```

I am using `tus-js-client` to test this (the demo) and it works perfectly fine with `tusd` (in Go). This problem only occurs with `tus-node-server`.

My server is only a copy paste of the Quick Start code provided in the README under "Build a standalone server".

Uploading files works fine too, but never resumes correctly, it always starts from the beginning.

**Comment by bhstahl** [comment]
Thanks for your help @davidgourde, added in [tus-node-server@0.1.3](https://www.npmjs.com/package/tus-node-server).
