### ISSUE TITLE
Running Nest 9 vs 7 with Tus.

### ISSUE THREAD

**Issue by paulm17** [tus/tus-node-server#434]
I'm having an issue running Nest greater than version 7.

If I upgrade to 9, I encounter the following 3 issues - all except the 3rd are solved:

1 - https://github.com/tus/tus-node-server/issues/84
2 - https://github.com/tus/tusd/issues/441
3 - https://github.com/tus/tusd/issues/452

I don't have any issues with NestJS v7, it just works.

Has anyone upgraded to v9?  Thanks

**Comment by paulm17** [comment]
@Murderlon Thanks for the reply, appreciate it.

Yes.

```
"@tus/server": "1.0.0-beta.5",
"@tus/file-store": "1.0.0-beta.1",
```

**Comment by Murderlon** [comment]
Can you provide as much details as possible? Integration code with Nest, errors you see logged, anything else that might help.

**Comment by paulm17** [comment]
Closing this as I have migrated over to a docker instance of tusd.  I'm already running various docker instance and doesn't hurt to run an extra one.  It was fairly painless to configure things like upload dir, storage location and employ hooks.  😄
