### ISSUE TITLE
[URGENT] Mixed Content, HTTPS & HTTP!

### ISSUE THREAD

**Issue by pexch** [tus/tus-node-server#442]
Hi there, I did some local testing and it worked, but sadly when I switched over to HTTPS, now I get the following errors:

`index-05617b65.js:11 Mixed Content: The page at 'https://domain.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain.com/files/99891fd7896b0fd361963190c93f3498'. This request has been blocked; the content must be served over HTTPS.`

server.js
```js
const tusServer = new Server({
    path: '/files',
    datastore: new FileStore({ directory: './tmp' }),
});
```

**Comment by Murderlon** [comment]
@phillip-causing is correct. Let me know if you still have issues.
