### ISSUE TITLE
@tus/s3-store: fix invalid character errors for "x-amz-meta-file” header

### ISSUE THREAD

**Issue by Murderlon** [tus/tus-node-server#458]
It seems we may naively stringifying a file here:

https://github.com/tus/tus-node-server/blob/0af377dfc4877b44c95238a3b46d96429cad96ca/packages/s3-store/index.ts#L429

Instead of stringifying the entire Upload, we may want to put all keys individually inside the metadata.

**Comment by ashitikov** [comment]
Hey, I have the same problem by using s3-compatible store cloudflare r2:
```
Invalid character in header content ["x-amz-meta-file"]
```
What causes this issue, is there a workaround?

**Comment by Murderlon** [comment]
Probably happens when weird ascii characters are used in file names or metadata. I'll probably take a look this week.

**Comment by Acconut** [comment]
👍 In tusd, we only store values from `Upload-Metadata` in the S3 object's meta data. So stuff like `isDeferred`, `size` etc. is not included at all.
