### ISSUE TITLE
Files are uploaded with an ID instead of a name, how do I know the name/url to list/download?

### ISSUE THREAD

**Issue by davidgourde** [tus/tus-node-server#46]
As the topic says, the files uploaded with `tus-node-server` are saved on the server side using an ID as the fileName. But I need to list the files that are on the server and let the user download them (not only list the new uploads, but list all uploaded files). Is there a way to get the list of files on the server, including their name and url?

Thank you.

**Comment by bhstahl** [comment]
@davidgourde You could create a get handler on you implementation that could do it. Something like

```js
const server = new Server();
server.get('/uploads', (req, res) => {
    // Depending on what data store you're using, list all files
    // in the uploaded directory. If your using FileStore, something like:
    fs.readdir(server.datastore.path, (err, files) => {
        // Format the JSON you want and send it in the res
    }
});
```

I'll add some documentation in the README for [get handlers](https://github.com/tus/tus-node-server/blob/938ee0f2107250d022cf9fd9a8a9c2614b01cb39/lib/Server.js#L90-L101). Will that work? 

We might need to add regex path support for the url's though so you could do

```js
server.get('/uploads/*', (req, res) => {
    // Send the file
});
```

Feel free to open up a PR with that if you need it!

**Comment by davidgourde** [comment]
Hi, thank you for the answer, but I am not sure of how the FileStore works. I am using the QuickStart example under "build a standalone server yourself". All I get in the files directory is the files with the ID as their name. I am unsure of where is the list of files the FileStore is using and how to read it to list the files with their names and url. Sorry if this is obvious, but I cannot seem to understand how it works.

**Comment by tameribrahim** [comment]
I have the same issue, using the express middleware! The problem I can't find the real filename anywhere!
Model : File class is 
```
this.id = `${file_id}`;
this.upload_length = upload_length;
this.upload_defer_length = upload_defer_length;
this.upload_metadata = upload_metadata;
```
Uploaded files named with the file_id with no extension!!!

**Comment by bhstahl** [comment]
@davidgourde @tameribrahim  I would take a look at how the node [`fs` module](https://nodejs.org/api/fs.html) works, as that might be useful for your application and/or tus implementation.  That said, here's how you could make a custom route on your tus server which would list all files that have been uploaded to your server.

```js
const path = require('path');
const fs = require('fs');

const server = new tus.Server();
const host = '127.0.0.1';
const port = 8000;
server.get('/uploads', (req, res) => {
    const files_path = path.join(process.cwd(), server.datastore.path);
    fs.readdir(files_path, (err, files) => {
        const response = { files: []};
        files.forEach((filename) => {
            response.files.push({
                name: filename,
                url: `http://${host}:${port}/${filename}`,
            });
        });
        res.writeHead(200);
        res.write(JSON.stringify(response));
        res.end();
    });
});
```

Then, navigate to http://127.0.0.1:8000/uploads to see that json response. This is just an example though as the urls in the above code don't link to anything actually serving the file. We would need to add regex routing (like below), which you're welcome to start building if you'd like!

```js
server.get('/uploads/*', (req, res) => {
    // Send the file
});
```

Additionally, you can provide a [custom naming function](https://github.com/tus/tus-node-server#custom-file-names) to your instance, if you would like to configure how the file names are created:
```js
const fileNameFromUrl = (req) => {
    return req.url.replace(/\//g, '-');
}

server.datastore = new tus.FileStore({
    path: '/files',
    namingFunction: fileNameFromUrl
});
```

**Comment by davidgourde** [comment]
Thanks a lot for the informations.

**Comment by kvz** [comment]
Please be careful using filenames for storage though, there's a reason why hashes are used. More was given in a similar question in https://github.com/tus/tusd/issues/60#issuecomment-241972080
