### ISSUE TITLE
Why there is no PRE-FINISH in EVENTS

### ISSUE THREAD

**Issue by prajilk** [tus/tus-node-server#467]
Is there anything I can do to pass a custom response like in PRE-FINSIH tusd Hook, where an upload is fully finished and validate or post-process an uploaded file then sent the response returned to the client.

**Comment by Murderlon** [comment]
Yes, you can use [`onUploadFinish`](https://github.com/tus/tus-node-server/tree/main/packages/server#optionsonuploadfinish) as per the docs.

**Comment by Murderlon** [comment]
Note that post-processing failures are ignored in both tusd and tus-node-server: https://github.com/tus/tus-js-client/issues/557
