### ISSUE TITLE
HTTPS being overridden to HTTP

### ISSUE THREAD

**Issue by divyanshverma** [tus/tus-node-server#469]
Environment:  
Server: Nodejs, Express

Everything works as expected over http. However over https, it rewrites the protocol to http:

See the image below. The request was made over https but Location headers is http. This creates the mixed content issue and access problems.

<img width="1724" alt="Screenshot 2023-08-22 at 9 45 37 PM" src="https://github.com/tus/tus-node-server/assets/13277557/8c54107d-9511-44f1-af25-4aacc2f7f138">

**Comment by Murderlon** [comment]
The problem is we have it as a default here:

https://github.com/tus/tus-node-server/blob/0af377dfc4877b44c95238a3b46d96429cad96ca/packages/server/src/handlers/BaseHandler.ts#L35-L70

Which I think makes sense. But there should probably be an option to switch the default.

**Comment by andywirv** [comment]
I also hit the error with the Location header switching to HTTP with the service is behind an HTTPS Load Balancer.  The initial create request will work over HTTPS but the upload fails as it relies on the value returned in the `Location` header.
Setting `options.relativeLocation: true` made this work as no scheme is included in the `Location` header
https://github.com/tus/tus-node-server/tree/main/packages/server#optionsrelativelocation

**Comment by Murderlon** [comment]
AFAIK when running behind a reverse-proxy, it's better to let the proxy add `X-Forwarded-Proto` and the server will respect it, rather than adding an another option to force override it regardless of the presence of a proxy.

What do you think?

**Comment by andywirv** [comment]
Relative location works well and I can't think of a downside to using it. Am I missing one(or many 😅)?

That said, respectForwardedHeaders is clearly there and documented for this purpose as you suggest. I just missed it. Easy to configure on Nginx and is included by default on GCP Load Balancers. 

https://cloud.google.com/load-balancing/docs/https#target-proxies

Maybe a little more effort in k8s ingress-nginx.

**Comment by Murderlon** [comment]
> Relative location works well and I can't think of a downside to using it. Am I missing one(or many 😅)?

I meant more rather than introducing a new option, like `forceHttpsLocation` or so, it's better to use `X-Forwarded-Proto`. If your use case is fine with relative location, then that's okay too!

So this issue can be closed then? I'm also okay with clarifying the docs if something is unclear.

**Comment by XavierJordaMurria** [comment]
I know this has been closed,
I am facing a similar issue here.
my POST request goes via HTTPS and succeeds but the following PATCH is switched to HTTP and it fails.
locally when working just with HTTP it works fine.

Could you please explain how I could update the tus-node-server so it uses the current protocol and not just HTTP?

many thanks

**Comment by D2rTech** [comment]
@Murderlon - my issue #550 is marked as duplicate, but we used respectforwardheader option and issue still persist.
What are the options now?

**Comment by andywirv** [comment]
@D2rTech what is the setup you are working with? If you are using https initially that means one or more reverse proxies/load balancers (as tus server does not support tls)

If you check the headers sent between each layer you will likely find the issue. When the headers mentioned above are sent it should work. Log the headers received by tus-server
