### ISSUE TITLE
server hook get metadata

### ISSUE THREAD

**Issue by cometta** [tus/tus-node-server#47]
server.on(EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
    console.log(event.file.upload_length);
   console.log(event.file.upload_metadata );
});

How to get event.file.upload_length and event.file.upload_metadata ? I can't get those value from event  hook complete. Possible to get my req.get(..) from event ?

**Comment by cometta** [comment]
Hi @bhstahl , let me know if you need more info on this.

**Comment by bhstahl** [comment]
Thanks @cometta, that should suffice. I'm a bit tied up at the moment with a few other projects, but i'll try to take a look soon. If you have any ideas, feel free to fork, fix and submit a PR with the patch!

**Comment by alolis** [comment]
I also agree that this is very useful

**Comment by alolis** [comment]
@bhstahl , if you have time please do check the reference above as well with some related thoughts. 

I noticed that you use `configstore` and store info related with the uploaded files in a `json` file so one possibility would be to attach the `metadata` as well and have it available during the completion event. I agree this might not be the best idea but the alternative is everybody to do their own thing.

An alternative can be to have the `configstore` as default, but allow for anyone to write his own "db tracking" adapter.

**Comment by alolis** [comment]
OK, there seems to be some confusion here. The metadata *are* attached to the event and are available when the `EVENT_UPLOAD_COMPLETE` triggers...

`FileStore` uses [configstore](https://www.npmjs.com/package/configstore) underneath which saves everything inside a `json` file. It would be nice to be able to pass an adapter to the `FileStore` which and store the data to different locations (e.g. Redis or a NoSQL db) instead of a plain text file.

**Comment by alolis** [comment]
@cometta , maybe this will help out a bit (it's ES6 syntax by the way):

````javascript
import _ from 'lodash';

// http://tus.io/protocols/resumable-upload.html#upload-metadata
const metadataStringToObject = (stringValue) => {
  const keyValuePairList = stringValue.split(',');

  return _.reduce(keyValuePairList , (metadata, keyValuePair) => {
    let [key, base64Value] = keyValuePair.split(' ');
    metadata[key] = new Buffer(base64Value, "base64").toString("ascii");;

    return metadata;
  }, {});
};

server.on(EVENTS.EVENT_FILE_CREATED, (event) => {
  console.log(metadataStringToObject(event.file.upload_metadata));
});
````

**Comment by cometta** [comment]
Hello @alolis 
 try this console.log(event.file.upload_metadata ) //    output:  undefined

**Comment by alolis** [comment]
@cometta , are you using the `metadata` object key on your [tus client](https://github.com/tus/tus-js-client#tusdefaultoptions)?

If you do not sent anything from the client then `upload_metadata` will be empty.

**Comment by cometta** [comment]
@alolis  

on the client

```
let upload = new tus.Upload(file, {
    metadata: { testmeta: 'something' }
  });
```

in the serverside
```
 app.all('/upload/*'), function(req, res) {
console.log("check metadata",req.get('metadata')); //undefined
});
```

```
server.on(EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
console.log(event.file.upload_length);
console.log(event.file.upload_metadata ); //undefined
});
```

**Comment by alolis** [comment]
@cometta, not sure what the problem might be. Seems to be working on my side with `tus-js-client` version `1.2.1` and `tus-node-server` version `0.2.1`.

**Comment by edwar64896** [comment]
I'm seeing this too. If I change to a FileStore on the back end, the metadata comes across. If I use GCS datastore, I can't see anything. Metadata is only sent (or visible) on the File Creation event.
