### ISSUE TITLE
HTTP assumed as part of POST response

### ISSUE THREAD

**Issue by stevewillard** [tus/tus-node-server#48]
Is there any particular reason why the POST handler includes 'http://' as part of it's response?
```javascript
const url = `http://${req.headers.host}${this.store.path}/${File.id}`;
```

Can this be changed to:
```javascript
const url = `//${req.headers.host}${this.store.path}/${File.id}`;
```

I'm running into a scenario where a POST is issued over HTTPS, and then the subsequent PATCH is over HTTP because of this.

**Comment by bhstahl** [comment]
Hey @stevewillard, thanks for submitting the PR. It was mostly because the server alone doesn't fully support https (#22). I'm assuming you have an ssl terminator in front of it?

**Comment by stevewillard** [comment]
Yes, that's right. For what it's worth, I have this changed running in production behind an ELB and it seems to work.
