### ISSUE TITLE
PATH requests are switched to HTTP

### ISSUE THREAD

**Issue by XavierJordaMurria** [tus/tus-node-server#489]
In my cluster, the POST is correctly done via HTTPS, but the following PATCH are switched to HTTP, and being blocked.

![image](https://github.com/tus/tus-node-server/assets/9607962/811d36fb-b610-4c79-8524-ddd07bfb7a17)
POST:
![Desktop-screenshot (1)](https://github.com/tus/tus-node-server/assets/9607962/37811dad-fe05-4a40-a481-e386657ec687)

PATCH:
![Desktop-screenshot](https://github.com/tus/tus-node-server/assets/9607962/2ff46428-3630-4f35-ab12-b695da6090e4)

Could you please advise how I could manage to get the tus-node-server to do the subsequent PATCH with HTTPS?

many thanks

**Comment by Murderlon** [comment]
As mentioned in the [other issue](https://github.com/tus/tus-node-server/issues/469) where you commented, you can use `relativeLocation` or `respectForwardedHeaders` and let your proxy add `X-Forwarded-Proto`

**Comment by XavierJordaMurria** [comment]
Thanks, for answering so quickly.
Yes that did the trick :)

**Comment by XavierJordaMurria** [comment]
Hi @Murderlon,
Allow me to ask you something else here.
After my PATCH upload times out, I was expecting it to trigger another PATCH and start from where it left it the previous one.

![Desktop-screenshot (2)](https://github.com/tus/tus-node-server/assets/9607962/d076f784-1e5c-44a8-a33d-cb2966f5005e)

But that is not the case.
Could you think of any reason why this may happen?
Many thanks in advance :)
