### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by avioli** [tus/tus-node-server#5]
> You should bug the author to publish it

**Comment by kvz** [comment]
Alright, @bhstahl :smile:

**Comment by bhstahl** [comment]
Sorry @avioli @kvz , been slightly bogged down with other work projects but this will be ready soon!

**Comment by bhstahl** [comment]
@avioli I tagged the remaining tasks with the [1.0 NPM Publish](https://github.com/tus/tus-node-server/milestones/1.0%20NPM%20Publish) milestone to give you a rough timeline. Feel free to pitch in if you're so inclined!

**Comment by avioli** [comment]
thanks

**Comment by bhstahl** [comment]
Published!

**Comment by kvz** [comment]
❤️
