### ISSUE TITLE
Server not finding files even though they are present inside the uploads dir

### ISSUE THREAD

**Issue by andrei27m** [tus/tus-node-server#536]
I have a simple setup like this
```typescript
const tusServer = new Server({
    path                   : '/uploads',
    datastore              : new FileStore({ directory: UPLOADS_DIR }),
    relativeLocation       : true, 
    respectForwardedHeaders: true, 
    tusServer.on(tusEvents.POST_FINISH, async (req, resp, event) => {...})
})

const server = express()
// ...
server.all('/uploads/*', async (req, res) => {
    return tusServer.handle(req, res)
})
```

This works initially. Uploaded files show up inside `/uploads` and tus finds them at the appropriate url `/uploads/<hash>`. But after a while tus no longer finds those files, responding instead with 404 "The file for this url was not found". The files themselves are still present in the `/uploads` directory, their permissions haven't changed, nothing is changed except that tus seems unable to find them.

I should add that I'm running this server inside a docker container. As far as I can tell this doesn't seem to be a factor since all files inside `/uploads` _are_ readable from twithin he container.

**Comment by Murderlon** [comment]
Hi, do you have a fast way to reproduce this? What is "after a while"?

**Comment by fenos** [comment]
are you running multiple docker containers?

**Comment by fenos** [comment]
Hey @andrei27m i'm closing this issue for now as we need more info to reproduce the problem you are having.
Feel free to comment below with the steps to reproduce it, we'll be happy to re-open and investigate.

So far everything seems good on our end.

**Comment by Tharusha-dev** [comment]
Hi, im also getting this error. And im runnin multiple containers and the vps is behind nginx.

This is my nginx conf

```

    location /files/ {
        proxy_pass http://172.17.0.4:1080;
     # Disable request and response buffering
        proxy_request_buffering  off;
        proxy_buffering          off;
        proxy_http_version       1.1;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header         Upgrade $http_upgrade;
        proxy_set_header         Connection "upgrade";
        client_max_body_size     0;

}
```

and my server code


```
const { Server } = require('@tus/server');
const { FileStore } = require('@tus/file-store');
const express = require('express');

const host = '0.0.0.0';
const port = 1080;
const app = express();
const uploadApp = express();

const server = new Server({
  path: '/files',
  datastore: new FileStore({ directory: '/files' }),
});

// Middleware to log all incoming requests
uploadApp.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.originalUrl}`);
  next(); // Pass control to the next middleware or route handler
});

uploadApp.all('*', server.handle.bind(server));
app.use('/files', uploadApp);

app.listen(port, host, () => {
  console.log(`Server listening on http://${host}:${port}`);
});
```
In the frontend I'm using uppy

`const [uppy] = useState(() => new Uppy().use(Tus, { endpoint: 'https://app.chatzu.ai/files/' }));`

the frontend does these requests in order

```
Request URL:
https://app.chatzu.ai/files
Request Method:
POST
Status Code:
301 Moved Permanently
Remote Address:
165.232.171.223:443
Referrer Policy:
strict-origin-when-cross-origin


Request URL:
https://app.chatzu.ai/files/
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
165.232.171.223:443
Referrer Policy:
strict-origin-when-cross-origin
```

Thanks
