### ISSUE TITLE
Track server-side upload progress

### ISSUE THREAD

**Issue by TimoStolz** [tus/tus-node-server#539]
I'd like to track upload progress in a database. Maybe, there could be a hook that fires every 10KB, while data is received. Maybe, this could be attached to `proxy` [here](https://github.com/tus/tus-node-server/blob/093efd7da196c99c5d6fcbdb1223684be5fbcd04/packages/server/src/handlers/BaseHandler.ts#L150).

Maybe you are wondering, why I'd like to persist progress of running uploads. I have an application with several users, submitting large files that take a long time to submit. I'd like to show all their running uploads on an overview page, along with progress.

**Comment by fenos** [comment]
You can already achieve this by querying the HEAD endpoint of TUS and using the `Upload-Offset` header returned in the response to determine the current progress of a file upload

**Comment by fenos** [comment]
Closing for now, let me know if the above solution works for you
