### ISSUE TITLE
metdata example uses undefinded validateMetaData function

### ISSUE THREAD

**Issue by dpmillerau** [tus/tus-node-server#546]
The validateMetadata function referred to in this example code isn't defined!

**const {Server} = require('@tus/server')
// ...

const server = new Server({
  // ..
  async onUploadCreate(req, res, upload) {
    const {ok, expected, received} = validateMetadata(upload)
    if (!ok) {
      const body = `Expected "${expected}" in "Upload-Metadata" but received "${received}"`
      throw {status_code: 500, body} // if undefined, falls back to 500 with "Internal server error".
    }
    // We have to return the (modified) response.
    return res
  },
})**

**Comment by Murderlon** [comment]
Hi, it's pseudo-code to illustrate you could do something yourself, like a `validateMetadata` function or whatever.
