### ISSUE TITLE
CRC errors using @google-cloud/storage 7.7.0

### ISSUE THREAD

**Issue by dpmillerau** [tus/tus-node-server#548]
gcs-store package.json allows any version of @google-cloud/storage, but demo builds with 6.12.0 and works (once patched). 

Building with 7.7.0 of @google-cloud/storage gives error 
CRC32 missing from the final portion of a resumed upload

This was on resumable with a chunk size.

forcing a version 6 revision of storage fixes the issue for now as a work around.

**Comment by dpmillerau** [comment]
reproduced by building with 7.7.0 of the google storage module.

**Comment by kantorcodes** [comment]
> reproduced by building with 7.7.0 of the google storage module.

Experiencing this as well! Any updates on this?
