### ISSUE TITLE
 S3-store doen't work with  Cloudflare R2 storage

### ISSUE THREAD

**Issue by sagargg** [tus/tus-node-server#560]
**Problem:**
I'm attempting to set up [s3-store](https://github.com/tus/tus-node-server/tree/main/packages/s3-store) with Cloudflare R2 storage. However, it seems that the current implementation does not support R2 due to `x-amz-tagging-directive` header.

**Expected Behavior:**
I expect s3-store to work seamlessly with Cloudflare R2 storage too. 

**Current Issue:**
The issue arises because R2 does not yet support the `x-amz-tagging-directive` header.

**Steps to Reproduce:**
1. Setup tus server with s3-store with Cloudflare R2 storage.
2. Observe the failure due to the lack of support for the `x-amz-tagging-directive` header.

**Screenshots:**
<img width="1366" alt="Screenshot 2024-01-19 at 2 37 37 PM" src="https://github.com/tus/tus-node-server/assets/87696933/6ff50ea9-23d3-4793-bcd9-197c5732f529">

**Comment by fenos** [comment]
@sagargg a new option has been added recently which allows you to disable tags.
Please use:

```ts
new S3Store({
  ...restOptions
  useTags: false
})
```

**Comment by sagargg** [comment]
@fenos Great,  Thank you 🙏
