### ISSUE TITLE
Upload fail after 10min request

### ISSUE THREAD

**Issue by orisailes** [tus/tus-node-server#576]
First, i am not using the resumable uploads because of [this bug](https://github.com/tus/tus-node-server/issues/521).

When my users trying to upload a file for more then 10+- minutes, they are getting an error with status 404. for me it seems like timeout error.
I tried to adjust the `req.setTimeout` function in the express, but unfortunately with no success. i did change the timeout but it has limitation so i thought it might be a client side timeout, but i cannot change the client side timeout because it is not possible with [tus-js-client](https://www.npmjs.com/package/tus-js-client) 

1. Use tus-js-client, tus/server and tus/gcs-store
2. Start upload, use Slow 3G internet upload speed (or lower) to mock a very slow upload
3. See error after 10.9 minutes

More about the error:
Request timings: 
![image](https://github.com/tus/tus-node-server/assets/77921279/e818895a-f065-452b-8364-4b046170477d)
Request details:
![image](https://github.com/tus/tus-node-server/assets/77921279/d66c1d5d-c2d4-4ea6-be16-145216e952c0)
*notice that `Keep-Alive:timeout=5` has no role here though its return from the BE side (witch the timeout is controlled properly there.. i guess)

**Setup details**
Please provide following details, if applicable to your situation:

- Runtime environment: Google Chrome
- Versions: 
```
 "@tus/gcs-store": "^1.0.1",
 "@tus/server": "^1.0.1",
 "tus-js-client": "^3.1.3", 
```

**Comment by fenos** [comment]
Hello @orisailes are you able to log the error you are getting with:

```ts
const tusServer = new Server({
  path: "/files",
  datastore: s3Store,
  onResponseError: (req, res, err) => {
      console.error(err)
  }
});
```

That would tell us what the underline timeout / problem could be

**Comment by fenos** [comment]
could you also update tus-node-server to the latest version please?
newer versions has received significant improvements
