### ISSUE TITLE
tus-node-server and ietf

### ISSUE THREAD

**Issue by mshafqatprofico** [tus/tus-node-server#586]
does this supports latest draft of ietf resumable upload or is there a plan to implement.

**Comment by Murderlon** [comment]
I think I'd like to add support for it as it hits working group final call. Supporting draft versions is a bit tricky, as you either make breaking changes for each new draft, or add more complexity to handle multiple versions.

From a developer and user perspective it doesn't really add much, it's just internals that change.

**Comment by mshafqatprofico** [comment]
will it be possible without the support of 104 status code as an intermediary response in node and then 201 created.

**Comment by Murderlon** [comment]
You're still going to need a client-side library I think. `fetch` in the browser for instance doesn't expose informational responses. Other than that, from my understanding, at least the major proxies support it as it moves through the network.

So unless you were hoping to use it directly in the browser, I think you'll be fine with the `104` status code.

**Comment by Acconut** [comment]
The informational response is not necessary. A client can send an empty upload creation request and then resume the upload using the returned upload URL, just like how tus uploads are done today.

**Comment by mshafqatprofico** [comment]
I want to support ios clinet which will be using NSURLSession with resumable background upload as introduced in ios17.below is the video related to resumable upload implemented in ios which expects 104 response. its discussed from 10th minute onward.
https://developer.apple.com/videos/play/wwdc2023/10006/

**Comment by Murderlon** [comment]
You can try tusd which supports the latest draft: https://tus.io/blog/2023/09/20/tusd-200#support-for-the-new-ietf-protocol

**Comment by mshafqatprofico** [comment]
yes, i have checked these example in go and swift and since our backend stack is written in js, i wondered if same could be achieved using node.

**Comment by mshafqatprofico** [comment]
unfortunately not with node. this could help but this will require different backend stack to handle resumable background upload. so i put this on hold.

**Comment by Murderlon** [comment]
As I mentioned before:

> I think I'd like to add support for it as it hits working group final call

From the feedback from the latest sessions I think we're close to reaching that, probably this year. But if you need something _right now_ I wouldn't wait for tus Node.js.

**Comment by mshafqatprofico** [comment]
@Murderlon yes, it will be a great feature to add.
