### ISSUE TITLE
Consider server and browsers with creation url

### ISSUE THREAD

**Issue by bhstahl** [tus/tus-node-server#59]
Right now the creation extension [omit's thee protocol](https://github.com/tus/tus-node-server/blob/be1e716f26945ef4bf8abb8d546a456fa356efa2/lib/handlers/PostHandler.js#L18) from a created url, which can cause some issues using tus-js-client server side (https://github.com/tus/tus-java-client/issues/10#issuecomment-258384118). We should consider a new approach that works in the browser and server

**Comment by Acconut** [comment]
tusd will derive the protocol from the request (https://github.com/tus/tusd/blob/master/unrouted_handler.go#L633-L637). Later this value may be overwritten by the X-Forwarded-Proto header (https://github.com/tus/tusd/blob/master/unrouted_handler.go#L645-L647) which is commonly used by proxies. A similar approach may be useful tus-node-server.

**Comment by bhstahl** [comment]
Like that option @Acconut, we'll follow suit
