### ISSUE TITLE
Is there a way to pass variables between the `onUploadCreate` and the `onUploadFinish` functions?

### ISSUE THREAD

**Issue by sammibajrami** [tus/tus-node-server#593]
I have figured out a way to do it but it's very awkward and also involves changing and adding a few lines in the  `@tus/server/dist/handlers/PostHandler.js` file.

Basically the way that I have it working is that you update the "Upload-Metadata" header of the `res` object in the `onUploadCreate` function.
This header is then parsed in the `PostHandler.js` file and the result overwrites the `upload.metadata` variable, and then the upload object passes the extra metadata to the `onUploadFinish` function.

Any chance that there is a better way already built in that I'm missing?

Thank you in advance!

**Comment by Murderlon** [comment]
Hi, this is an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem/66378#66378). What is the problem you are trying to solve? Are you only communicating between hooks or does the client also need to know this value?

Maybe you can just do it in server memory with a `Map`. Or if it needs to survive server restarts, put it in something like Redis?

**Comment by sammibajrami** [comment]
I'm sorry, here is the problem:
I need to pass a variable from the `onUploadCreate` function to the `onUploadFinish` function. It does not need to be sent back to the client.

Is there a way to do this?

If not, then I'll look into your other suggestions, thank you!

**Comment by Murderlon** [comment]
I don't know the requirements and why you are trying to pass that variable. There are many ways to write/read to different things depending on what you are doing, but those all fall into your hands and setup, there is no built-in way of doing this.

**Comment by sammibajrami** [comment]
I'm sorry for being unclear.

I'm using the `onUploadCreate` function to validate the upload request, a process that generates a unique ID that I need to get in the `onUploadFinish` function.

Redis would be a way to do this, but I was hoping that I could simply update the metadata of the upload, but it sounds like that is not an option, correct?

**Comment by Murderlon** [comment]
If you tell me why you need the ID to be accessible by the `onUploadFinish` hook, we can see if there are alternative approaches.

You can't change the metadata in `onUploadCreate` in a way that's persisted in the store too. We may want to support that at some point.

**Comment by sammibajrami** [comment]
Once the upload is completed I create an entry for it, that includes the unique ID, in a separate database.

I'd be happy to share the code that I wrote to make the changes to the `upload` object persistent or even make a pull request if you think it'd help.
I've got it down to just adding two lines and changing two lines in the `tus-node-server/packages/server/src/handlers/PostHandler.ts` file.

The main issue with my approach is that the changes do not persist all the way back to the client (which isn't necessary in my case, but still).

**Comment by Murderlon** [comment]
> Once the upload is completed I create an entry for it, that includes the unique ID, in a separate database.

Can't you just validate the upload in `onUploadCreate`, reject if needed, and only create and store the ID in `onUploadFinish` without the need to communicate between hooks?

**Comment by sammibajrami** [comment]
I would, but the ID is created as part of the validation process.
I'll just create a fork for myself with those small changes I mentioned, it should be simple to keep up to date with the main repo.

That said, would you like me to create a pull request with those changes?

The way it works is that the `onUploadCreate` function returns both the `res` object and the `upload` object to the `PostHandler` which then overwrites the `upload` object in that file same as the `res` object.

I'm not sufficiently familiar with the whole codebase to be sure that that's the best way to do it, what do you think?

**Comment by sammibajrami** [comment]
For reference, here is the updated code:
```
        let upload = new models_1.Upload({
            id,
            size: upload_length ? Number.parseInt(upload_length, 10) : undefined,
            offset: 0,
            metadata,
        });
        if (this.options.onUploadCreate) {
            try {
                const afterUploadCreate = await this.options.onUploadCreate(req, res, upload);
                res = afterUploadCreate[0];
                upload = afterUploadCreate[1];
            }
            catch (error) {
                log(`onUploadCreate error: ${error.body}`);
                throw error;
            }
        }
```

**Comment by sammibajrami** [comment]
Here is the fork: https://github.com/sammibajrami/tus-node-server

**Comment by Murderlon** [comment]
Thanks for sharing. We can't allow to override the entire upload, only metadata should be allowed, and the metadata should be validated as well. It's also important to make it backwards compatible to prevent a breaking change.

I'll take next week probably. Created an issue: https://github.com/tus/tus-node-server/issues/594
