### ISSUE TITLE
Allow hooks to override metadata 

### ISSUE THREAD

**Issue by Murderlon** [tus/tus-node-server#594]
Allow hooks to override metadata, only metadata not other `Upload` properties, in a backwards compatible way to precent breaking changes in the hook design. New metadata should probably be validated as well.

**Comment by Acconut** [comment]
In tusd, a pre-create hook can return a [FileInfoChanges object](https://pkg.go.dev/github.com/tus/tusd/v2/pkg/handler#FileInfoChanges), which allows the hook to customize a selected set of properties. Maybe this can serve as an inspiration for tus-node-server.
