### ISSUE TITLE
Split into single packages

### ISSUE THREAD

**Issue by psi-4ward** [tus/tus-node-server#61]
Hi,
I cant use tus-node-server because `google-gax` raises compile errors.
But the case is, I don't need any store (or rather implement my own) so it would be really good to split it up into single packages:

* tus-server
* tus-server-store-fs
* tus-server-store-google
* tus-server-store-gridfs
etc...

**Comment by bhstahl** [comment]
I've been thinking about doing this but haven't had the need yet. I'm all for it!

**Comment by bhstahl** [comment]
Kicking off this ticket with:

- [tus-datastore-abstract](https://www.npmjs.com/package/tus-datastore-abstract)
- [tus-datastore-filesystem](https://www.npmjs.com/package/tus-datastore-filesystem)
- [tus-datastore-gcs](https://www.npmjs.com/package/tus-datastore-gcs)

**Comment by bhstahl** [comment]
Would love to hear your thoughts on this @radev

**Comment by Murderlon** [comment]
Done in #351
