### ISSUE TITLE
Allow setting custom paths for the configstore

### ISSUE THREAD

**Issue by psi-4ward** [tus/tus-node-server#62]
Storing Metadata in `~/.config/configstore` is rather impractical.
You should at least provide an option to set the path.

**Comment by bhstahl** [comment]
Completely agree. Feel free to open a PR with that option!

**Comment by ThomasG77** [comment]
In fact, "Allow setting custom paths for the configstore" is about changing `configstore` with another solution. To quote [configstore package](https://www.npmjs.com/package/configstore), 

> Easily load and persist config without having to think about where and how

If you don't want the default path, just don't use `configstore` package.
I will try to come back with a more solution oriented comment soon.

**Comment by kvz** [comment]
Perhaps https://www.npmjs.com/package/rc is helpful here?

**Comment by Acconut** [comment]
You should be able to change the configuration directory using the `XDG_CONFIG_HOME` environment variable (we are using [configstore](https://github.com/yeoman/configstore/blob/master/readme.md) internally which can be configured in that way).

That being said it might still be beneficial to switch to another storage mode.

**Comment by Murderlon** [comment]
It's now possible to provide your own configstore.
