### ISSUE TITLE
S3store creating extra .info file 

### ISSUE THREAD

**Issue by sagargg** [tus/tus-node-server#627]
Hi, While uploading to S3 storage using S3Store, an extra .info file is created with each upload. Why is it creating this file, and what is it used for? Is there a way to get rid of the .info file?
Eg.  <img width="827" alt="Screenshot 2024-06-13 at 1 35 02 PM" src="https://github.com/tus/tus-node-server/assets/87696933/ee1bbad8-0cd7-4458-98ef-9da8e2707f99">

**Comment by Murderlon** [comment]
Hi, we need to be able to store additional information, such as metadata, storage info, offset, size, creation date. We make requests against the info file to know those things. Generally you keep the file names randomly generated (like the default), without file extension even, as you have that information separate and this way you prevent file corruption with same names.
