### ISSUE TITLE
How can i get original filename?

### ISSUE THREAD

**Issue by Ivan-Feofanov** [tus/tus-node-server#63]
Hi all. 
How can i get original filename?
In file object i get only
`{ file: 
   File {
     id: '-',
     upload_length: '3957145',
     upload_defer_length: undefined,
     upload_metadata: undefined } }
`

**Comment by Ivan-Feofanov** [comment]
Okay, i find something like solution
```
const fs = require('fs')
const path = require('path')
const tus = require('tus-node-server')

const server = new tus.Server()

const storageFolder = path.join(process.cwd(), '/files')

server.datastore = new tus.FileStore({
    path: `/${storageFolder}`
})

const metadataStringToObject = (stringValue) => {
  const keyValuePairList = stringValue.split(',')

  return keyValuePairList.reduce((metadata, keyValuePair) => {
    let [key, base64Value] = keyValuePair.split(' ')
    metadata[key] = new Buffer(base64Value, "base64").toString("ascii")

    return metadata;
  }, {})
};

server.on(tus.EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
  fs.rename(`${storageFolder}/${event.file.id}`, `${storageFolder}/${metadataStringToObject(event.file.upload_metadata).filename}`)
})

const host = '0.0.0.0'
const port = 7000
server.listen({ host, port }, () => {
    console.log(`[${new Date().toLocaleTimeString()}] tus server listening at http://${host}:${port}`)
})
```
It may have an easier way?

**Comment by bhstahl** [comment]
Hey @Ivan-Feofanov, correct. The easiest way could be to require the original file name to be passed as [upload metadata](http://tus.io/protocols/resumable-upload.html#upload-metadata).

**Comment by djsg** [comment]
Hi,
tried your code, but let not defined reference error.
sorry, new to JavaScript.

**Comment by rictorres** [comment]
@djsg which version of `node` are you using?
`let` is a keyword like `var`

**Comment by djsg** [comment]
It's version 4.2.6.
Previously my system (Ubuntu 16.0.4) only has  nodejs; just now after I installed nodejs-legacy, I can use node to start Ivan's code without any problem. Both have same version number.
I need to google "node vs nodejs". Haha.

**Comment by rictorres** [comment]
@djsg i see what's wrong:

you're calling `fs.rename()` without providing a callback for it (`fs.rename(oldPath, newPath, callback)`), so you'd write it like:

```
server.on(tus.EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
  fs.rename(`${storageFolder}/${event.file.id}`, `${storageFolder}/${metadataStringToObject(event.file.upload_metadata).filename}`, (err) => {
	// handle error in here
	console.error(err)
})
```

there's also the `sync` version of `rename` although i wouldn't recommend in this case.

ref: https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_rename_oldpath_newpath_callback

**Comment by djsg** [comment]
@rictorres 
Thx for your help. Now I get it to work.

**Comment by Acconut** [comment]
You pass `oldpath` to `console.log` in your callback, but the variable is called `oldPath`. Notice the capitalization. In JavaScript variable names are case sensitive, so oldpath is not oldPath.

**Comment by Acconut** [comment]
No worries, you're welcome :)

**Comment by FaizalDwi** [comment]
hi, i tried those codes and i still get my filename "undefined" instead of the original name after uploaded. i use **Uppy tus** as front-end.
 this is my code from server.js

`
const fs = require('fs')
const path = require('path')
const tus = require('tus-node-server')

const server = new tus.Server()

const storageFolder = path.join(process.cwd(), '/uploads')

server.datastore = new tus.FileStore({
    path: `/${storageFolder}`
})

const metadataStringToObject = (stringValue) => {
  const keyValuePairList = stringValue.split(',')

  return keyValuePairList.reduce((metadata, keyValuePair) => {
    let [key, base64Value] = keyValuePair.split(' ')
    metadata[key] = new Buffer.from(base64Value, "base64").toString("ascii")

    return metadata
  }, {})
}

server.on(tus.EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
  const oldPath = `${storageFolder}/${event.file.id}`
  const newPath = `${storageFolder}/${metadataStringToObject(event.file.upload_metadata).filename}`
  
  fs.rename(oldPath, newPath, (err) => {
    // handle error in here
    if(err != null)
        console.error(err)
    else {
        console.log('file ' + oldPath)
        console.log('saved as ' + newPath)
    }
  })
})

const host = '127.0.0.1'
const port = 1080
server.listen({ host, port }, () => {
    console.log(`[${new Date().toLocaleTimeString()}] tus server running at http://${host}:${port}`)
})
`

did i make mistake from that code?

**Comment by Acconut** [comment]
@FaizalDwi I do not see any immediate error. What is the value of `event.file.upload_metadata`?

**Comment by FaizalDwi** [comment]
> @FaizalDwi I do not see any immediate error. What is the value of `event.file.upload_metadata`?

it solved already. i changed into into 'name', instead of 'filename'
`server.on(tus.EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
  fs.rename(`${storageFolder}/${event.file.id}`, `${storageFolder}/${metadataStringToObject(event.file.upload_metadata).name}`)
})`
