### ISSUE TITLE
EVENT_UPLOAD_COMPLETE emitted before file is flushed

### ISSUE THREAD

**Issue by mass85** [tus/tus-node-server#74]
I am under impression that EVENT_UPLOAD_COMPLETE is emitted before the uploaded file is properly stored in file system, because fs.readFile gets me frequently (and randomly) not all data from uploaded file. However when I read this file later, I get all data so there must be lack of synchronization.

Probably this https://github.com/tus/tus-node-server/blob/5943566baaadb7db3cdd8a37a3c6984ea82066ca/lib/stores/FileStore.js#L123 should be called on stream.end instead of req.end.

**Comment by bhstahl** [comment]
Thanks for using tus and submitting this @mass85. If you want to submit a pull request proposing the change (and further implications to requests) I'd be happy to take a look

**Comment by gerdus** [comment]
I made a pull request #79  that fixes this issue

**Comment by bhstahl** [comment]
Fixed in https://github.com/tus/tus-node-server/pull/79
