### ISSUE TITLE
Using path with Google Cloud Storage doesn't work

### ISSUE THREAD

**Issue by lostpebble** [tus/tus-node-server#76]
So I've set up a tus server using the Google Cloud datastore like so:

```
server.datastore = new tus.GCSDataStore({
    path: '/admin-tus-uploads',
    bucket: 'bucket-name',
});
```

It manages to get my credentials automatically because I'm using the GCloud SDK, which is great.

But, after making an upload I have noticed that all files are being saved into the root directory of the bucket, and not inside the subfolder / path I have defined as `/admin-tus-uploads`.

Am I doing something wrong? Is this not how `path` works in this case?

If I try and define the path in the `bucket` option it fails, understandably. So I'm at a loss for how to set a subfolder in a bucket for my GCS uploads.

**Comment by bhstahl** [comment]
hey @lostpebble, `/path` is actually just the path on your server for `POST` requests. 

The file created in [GCSDataStore.js](https://github.com/tus/tus-node-server/blob/104aa6b589a9df35ae142df3b235536f1833c89d/lib/stores/GCSDataStore.js#L94) is indeed in the root of the bucket. Feel free to submit a pull request adding that as an configurable option if you'd like?

**Comment by lostpebble** [comment]
@bhstahl ah, okay. Sure, I'll look into it more as my requirements need it. I think for now I'll make due with the root folder just to get things up and running.

**Comment by bhstahl** [comment]
Great, closing until there is a call to action.
