### ISSUE TITLE
PostHandler returns invalid 'Location' header

### ISSUE THREAD

**Issue by ujvzolee** [tus/tus-node-server#81]
Hi!
The following line seems to break the proper URL creation when uploading new files:

https://github.com/tus/tus-node-server/blob/7b7ac6c6c72f43559f9656848140794a4193ca1f/lib/handlers/PostHandler.js#L18

Suggestion:
The `req.baseUrl` should be used **together** with `store.path`.
```
const url = `//${req.headers.host}${req.baseUrl}${this.store.path}/${File.id}`;
```

**Comment by bhstahl** [comment]
Good catch @ujvzolee. Happy to merge a PR if you'd like to tackle this one.

**Comment by ujvzolee** [comment]
@bhstahl #85 
When can we expect the next release so I can update our deps?

**Comment by bhstahl** [comment]
Thanks @ujvzolee! Doing a release now
