### ISSUE TITLE
Error in get uploaded files

### ISSUE THREAD

**Issue by sharh** [tus/tus-node-server#84]
```javascript
const server = new tus.Server();
server.datastore = new tus.FileStore({
    path: '/files'
});
var uploadApp = express();
uploadApp.get('/uploads/:filename', (req, res)=>{
    console.log()
    res.download(path.resolve(__dirname, 'files/'+req.params.filename))
})
uploadApp.all('*', server.handle.bind(server));
app.use('/uploads', uploadApp);

```

> source code:
```javascript
// Check if this url has been added to allow GET requests, with an
// appropriate callback to handle the request
if (!(req.url in this.handlers.GET)) {
    res.writeHead(404, {});
    res.write('Not found\n');
    return res.end();
 }
```

Then in browser:

`http://localhost/uploads/07e9fe83e7a1a27e5766044615157080`，It says `Not found`

I think you should not use `(req.url in this.handlers.GET)`, it's bad!!!

**Comment by bhstahl** [comment]
@sharh the `GET` hander is very minimal as the primary concern of this repo is receiving uploads, not serving files. I made the assumption most developers would typically implement their own `GET` routing/handlers. 

That said, If you'd like to propose something more sophisticated in a PR, I'd be happy to review.

**Comment by sharh** [comment]
@bhstahl Em, Yes, you are right. I'd like to.

**Comment by jazkh** [comment]
@bhstahl 
Hello, I am facing the same problem. What should I do?

**Comment by Acconut** [comment]
>  What should I do?

As  @bhstahl said, you should implement your own GET handler.
