### ISSUE TITLE
How should we authorize users? 

### ISSUE THREAD

**Issue by dongmai** [tus/tus-node-server#88]
Currently anyone has the api endpoint can upload files to the server. Is there any way to enable authorization when uploading files?

I'm thinking about writing a middle-ware for this, a database will be made to store user's credentials. And that info is required on api request to authorize users.

Thanks

**Comment by kvz** [comment]
Related: https://github.com/tus/tus-node-server/issues/83

It's probably best to add middleware for this to an express server, and use tus-node-server in conjunction with that

**Comment by dongmai** [comment]
Ok, thanks @kvz
