### ISSUE TITLE
integration with feathersjs

### ISSUE THREAD

**Issue by musicformellons** [tus/tus-node-server#92]
Trying to setup with Feathers (which uses express) but having problems. Any suggestions how to get [this](https://stackoverflow.com/questions/48412192/integrate-tus-node-server-into-feathersjs-with-express) working?

**Comment by Acconut** [comment]
Unfortunately, no one in our team has experience with Feathersjs. Luckily, your question was answered in the linked StackOverflow question: https://stackoverflow.com/a/48534882
