### ISSUE TITLE
basic authentication through a HTTPS proxy

### ISSUE THREAD

**Issue by krampampuli** [tus/tus-node-server#99]
Hi, for this, I had to add the `Authorization` header to `lib/constants.js`, and also the corresponding function in `lib/validators/RequestValidator.js`:

```javascript
static _invalidAuthorizationHeader(value) {
    return false;
}
```

It works in my test environment, but I don't have direct access to the production server to use custom codes.

Could this be included in the master branch? Then I could ask for a server update. Than you!

**Comment by Acconut** [comment]
Apologies for the delay, this feature has been added in https://github.com/tus/tus-node-server/pull/103 and should be ready for use now.
